### ISSUE TITLE
Update webpack public path

### ISSUE THREAD

**Issue by sirreal** [Automattic/newspack-blocks#1]
Make sure you use a global variable that won't conflict with Jetpack or other plugins:
https://github.com/Automattic/newspack-blocks/blob/3872ece26b94127c6dc398c73a5c354697dd38e8/src/setup/public-path.js#L8

You'll need to make sure that the variable is available, here's how Jetpack handles that:

https://github.com/Automattic/jetpack/blob/43f02648806d6a927445e528a007176a76e31875/class.jetpack-gutenberg.php#L509-L513
https://github.com/Automattic/jetpack/blob/43f02648806d6a927445e528a007176a76e31875/class.jetpack-gutenberg.php#L600-L604

**Comment by sirreal** [comment]
The snippet I linked appears to be unchanged:

https://github.com/Automattic/newspack-blocks/blob/a91ffb7050bd2089b48bc3e7d7e16f7d0dcac7db/src/setup/public-path.js#L9-L13

It's the same global variable that Jetpack uses, but doesn't seem to be defined by anything in this repository. I'm assuming that the linked code doesn't do anything at all. If Jetpack were also running on the site it could cause conflicts and/or strange behavior.

This is all about the webpack dynamic path. If you haven't read the link in the comment that would be a good start: https://webpack.js.org/guides/public-path/#on-the-fly

This is important for assets that are loaded at runtime and not compiled into the bundle. Webpack needs to know where to find them so they can be requested. These are typically things like assets in the build (images or any [asset modules](https://webpack.js.org/guides/asset-modules/#root) that aren't inlined) or [dynamic imports](https://webpack.js.org/guides/code-splitting/#dynamic-imports) that you split up the bundle.

**Comment by adekbadek** [comment]
Weird stuff, I can't see why it was added. Proposing to remove in https://github.com/Automattic/newspack-blocks/pull/868.

**Comment by sirreal** [comment]
I suspect it was copied from Jetpack, this project started around the time Jetpack blocks were being heavily worked on by the same folks.
