### ISSUE TITLE
Homepage Blocks: Explore alternate approaches to block options

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#10]
Came up in feedback for #8.

@jeffersonrabb suggested one approach could be to use block styles:

> There’s lots of confusing options in the sidebar and I have an idea for how to clean up the UI. What if we used a series of  [Block Styles](https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-registration/#styles-optional)  to represent different configurations of fields rather then exposing toggles for everything? If we could narrow the layout options down to a manageable set (6?) the block style picker might be a nicer UI for this. Setting a block style simply sets a class on the block in the form of is-style-STYLE_NAME, but we can determine the class programmatically and use it to determine field visibility. 

Potential downsides:
* Depending how it's organized, it could limit what else block styles could be used for (eg adding background colours and borders)
* We can't conditionally hide block styles depending on other settings (something I ran into when trying to use the same thing for image alignment in the block). 

Another option could be to split the block into multiple blocks, with some options fixed to 'on' (for example, with image and without). 

Potential downsides:
* It could add a lot of noise to the Newspack section of the block picker.
* Being able to transform one block to another would be very important, so someone building a page wouldn't have to keep resetting options when checking what styles work best for them. 

This needs discussion and exploration to figure out the best approach.

**Comment by jeffersonrabb** [comment]
This issue, while still fundamentally valid, has been superseded by work on the Query block among other things. Closing.
