### ISSUE TITLE
Article Block: 5-6 columns don't look great

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#106]
This came up in the review of #105: 

The 5 and 6 column layouts for the article blocks don't look great:

![image](https://user-images.githubusercontent.com/177561/64276878-d0677680-cefd-11e9-8ea8-159a59a0c419.png)

Some options to improve them could be:

* Changing the breakpoint for when they drop to 2-3 columns from tablet to desktop.
* Doing something about the font sizing so they don't use larger font sizes (though my worry with this one is that it could be confusing, especially since there is a separate font size control. But we might be able to set a different 'starting' size that the font size control then scales up and down, but you can't get the same font size in the 6 column layout as you can with a 1 column layout).

**Comment by laurelfulford** [comment]
Something else that came up related to these column counts (and perhaps the four column option as well): 

These stories are small even on desktop; changing it to a single column on mobile makes them quite large, and really changes the visual hierarchy (especially the image size). We need them to 'break down' in a more appropriate way -- like stick to two columns, even on small screens.

**Comment by thomasguillot** [comment]
How about:

* We allow the block to display wide or full width
* If wide, then you get the 5 columns layout
* If full-width, you get the 5 && 6 columns layout
* If "normal" width, then we limit it to 4 columns

On tablet:
* 5 columns can translate to a row of 2 then a row of 3
* 6 columns -> 3, 3

On mobile:
* 5 columns -> 1, 2, 2
* 6 columns -> 2, 2, 2

**Comment by dkoo** [comment]
@laurelfulford is this still an issue? I think we adopted much of what you suggested already, right? Feel free to reopen if there's more to do.
