### ISSUE TITLE
Posts block: Editor preview with specific posts not in correct order

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-blocks#1092]
**Describe the bug**

The `orderby => post__id` when using the post block's specific-select mode [seems to have been lost in this refactor](https://github.com/Automattic/newspack-blocks/pull/1083/files#diff-18ac3a422b275b8a615ae833ec6195e506e59a8254ac8840818e515efd362391L329-L338). The [site frontend still shows the correct order](https://github.com/Automattic/newspack-blocks/blob/a613874a398ffed6cfbeb699a3d49c95bb559a5a/includes/class-newspack-blocks.php#L549-L550), but the editor preview will show a random order.

**To Reproduce**
1. Add posts block. Select specific posts. Observe editor preview is not in the order of the specific posts.

**Screenshots**

https://d.pr/i/osySZx/h8pG23g9MC

**Expected behavior**

The preview and frontend should be in the order that the specific posts are in the sidebar

**Comment by laurelfulford** [comment]
This was fixed with #1093; not entirely sure why the issue didn't close on its own, but closing it now!
