### ISSUE TITLE
Improve query panel

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#11]
With the query panel being such an important part of the Homepage Block, we have an opportunity to work on something more standardized that could become reusable. 

Came up in #8; from @jeffersonrabb: 

> With all the toggles removed, the sidebar would only contain Category and Count controls.  [@mtias](https://github.com/mtias)  pointed me to  [this issue](https://github.com/WordPress/gutenberg/issues/2662)  which envisions a Query component that would expose limit/sort/taxonomy to the user in a reusable way. We could build such a component specifically for this block and if all goes well propose it to core.

Some other possible query options:

* Orderby
* Posts by author.
* Posts by taxonomy.
* Pulling posts by 'Most Popular' could also be advantageous for Newspack, but may be less useful in a reusable component. 

This would be something to explore after #8 ships.

**Comment by jeffersonrabb** [comment]
My mistake here: I didn't realize that `QueryControls` existed already and the issue was long ago closed. Closing the issue—sorry for the confusion!
