### ISSUE TITLE
Option to change title of button in donate block

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-blocks#1145]
**Is your feature request related to a problem? Please describe.**
While discussing with @miguelpeixe for reader revenue update, came the idea of providing option to change title of donate button. This will be handy in future as more reader revenue features are added, hence to provide more flexibility to configure as per publisher revenue model.

**Describe the solution you'd like**
Option to change title of button in donate block.

**Additional context**

![169480388-a8092526-adc4-4dc6-805e-231933a42d44](https://user-images.githubusercontent.com/7325107/169688980-682d57dd-a035-42a9-b3c2-64397200c365.png)

**Comment by aschweigert** [comment]
YubaNet (one of the beta publishers) has asked for this as well, specifically they would like to change "Donate" to "Subscribe". I tried editing the block and I don't seem to be able to edit the button text directly...is there some other way to do it?
