### ISSUE TITLE
Article Block: Display as list

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#117]
Add an article style where it displays like a list, even if they are concurrent separate blocks (so you can handpick specific blocks, and still have them appear as a list).

**Comment by jeffersonrabb** [comment]
@laurelfulford does this refer to either the List View option or the Choose Specific Posts feature?

**Comment by laurelfulford** [comment]
I'm trying to remember what September-me was thinking, I think it was meant to be a list-like display for the homepage posts block, that, when you put more than one of them together, they are spaced in a way that it doesn't look like they're separate blocks. 

I'm not sure if the latter part would cause more problems than not, though :)

**Comment by dkoo** [comment]
Feel free to open if you want to revisit.
