### ISSUE TITLE
Store meta about manually related stories

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-blocks#1172]
We need a way for editors to manually indicate what stories are related to a current story — for example, a custom meta field in the post editor, allowing the author to select related stories. That information is then stored and can be displayed in a variety of places, tying into feature requests such as https://github.com/Automattic/newspack-blocks/issues/1108.

**Comment by adekbadek** [comment]
Closing as a duplicate of https://github.com/Automattic/newspack-blocks/issues/1177 – the functionality described here would be a part of solution to #1177 .
