### ISSUE TITLE
Custom posts

### ISSUE THREAD

**Issue by mmprep** [Automattic/newspack-blocks#1197]
I use the powerful CM Tooltip Glossary plugin intended to maintain a database of terms that are automatically highlighted on all posts where they have been found.

For each term, this plugin creates and uses a custom post called _glossary_.

If you could please answer the following questions:

1. Can I get Newspack Blocks to treat custom posts, particularly the _glossary_, like regular posts? Right now I can't get the _glossary_ on the homepage automatically because Blocks just can't see it.

2. Can I add a template selection option for the _glossary_? Right now they all have the default template type, but I'd like to change it to template One Column for example.

3. How in general is the situation with support of custom posts in Newspack?

**Comment by adekbadek** [comment]
HI!
 
1. The custom post type, when it's registered, has to declare support for the Homepage Posts block ([example with our Newsletters plugin](https://github.com/Automattic/newspack-newsletters/pull/393)). If you're not in control of the declaration of this "glossary" post type, it's not currently possible to include this post type in Homepage Posts block.

2. This sounds like a general WP question, unrelated to this plugin. You'll have more luck on [StackOverflow](wordpress.stackexchange.com/) or wordpress.org

3. That's a very broad question, not sure what to say.

**Comment by adekbadek** [comment]
I'll close the issue, because there's no plan to implement a solution to this particular problem now.

**Comment by mmprep** [comment]
Are there plans to support any custom posts in Newspack Block?

**Comment by mmprep** [comment]
@adekbadek Are there plans to universal support **any** custom posts in Newspack Block?

**Comment by adekbadek** [comment]
Any custom post is supported via `supports` parameter on `register_post_type` call. Other kind of support is not planned.
