### ISSUE TITLE
Duplicate post management

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#12]
This came up in the review for #8 from @jeffersonrabb.

We need a way to make sure posts are NOT duplicated across multiple sections when there is overlap in the homepage blocks.

This could be manually avoided by very careful section selection, or by having some kind of offset control, but having a programmatic way to handle it would be the least fragile.

We would also need to consider how this interacts with things like 'Most Popular' and 'Most Recent' post sets, or other sections that may need to be exempt.

**Comment by jeffersonrabb** [comment]
Resolved in https://github.com/Automattic/newspack-blocks/pull/289.
