### ISSUE TITLE
Article Block: Control font size of label

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#120]
Came in from staging site feedback -- it would be helpful if you could control the font size of the label.

I made it so the section header of the block would not change with the rest of the font size; I'm not sure the best way to approach this ask without creating some visual weirdness. It seems like it should have its own control, so it wouldn't always change.

**Comment by dkoo** [comment]
This is no longer relevant as the header text does change along with the font-size option now.
