### ISSUE TITLE
Donate (streamlined): Add a means of including a captcha

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-blocks#1209]
**Is your feature request related to a problem? Please describe.**

As it is now, the block and native checkout are vulnerable to card testing. We've seen a massive hit on one site already (120K attempts). For the standard donate block, we can add a reCaptcha to the checkout page. The reCaptcha extension doesn't work for this block. 

**Describe the solution you'd like**

Include a means of adding a captcha or a check to block bots and card testing attempts. 

**Describe alternatives you've considered**

None.

**Comment by adekbadek** [comment]
Stripe's docs: https://stripe.com/docs/disputes/prevention/card-testing

**Comment by yogeshbeniwal** [comment]
Captcha will be too much for news users as most of them are not so technical and it also add friction to payment, readers trying to find fire extinguishers on mobile screen :-)

Combination if couple of approach should stop automatic card testing and increase cost of attacker's efforts

- Passing as much Client and Customer Signals to Stripe API for detection
- Session validation using CSRF token

**Comment by tmmbecker** [comment]
Noting that YubaNet and Grice Connect have both now been hit with card testing spam through the simplified donate block.

**Comment by tmmbecker** [comment]
From [Stripe's docs](https://stripe.com/docs/disputes/prevention/card-testing#mitigations), @claudiulodro  suggests this approach:

> integrating with Stripe’s recommended integration enables us to run CAPTCHA automatically on suspected card testing charges

**Comment by dkoo** [comment]
#1234 has a working implementation with reCaptcha v3, which is a frictionless form of CAPTCHA.

**Comment by adekbadek** [comment]
Closed by #1234
