### ISSUE TITLE
Always missing one post regardless of settings

### ISSUE THREAD

**Issue by ahegyes** [Automattic/newspack-blocks#1217]
**Describe the bug**
A user came in via ticket (5428162-zd-woothemes) to mention that regardless of their settings, one blog post is always missing on their home page. They are using the *Blog posts* block.

After some troubleshooting, here's the behavior:

* If the blog has sticky posts, the latest sticky post will be missing
* If the blog does not have any sticky posts, the latest post, in general, will be missing

This is even more confusing since 'ignore_sticky_posts' seems to be always true (https://github.com/Automattic/newspack-blocks/blob/master/includes/class-newspack-blocks.php#L560) and thus all sticky posts should've been ignore always regardless.

**To Reproduce**
In this particular case:
* Have 30 published blog posts
* Edit the home page via FSE to include a "Blog posts" block that displays 100 posts
* Only 29 posts will show -- the missing one is based on the logic presented above

**Expected behavior**
All 30 published posts should show up (maybe? I'm not sure how sticky posts play into all this, but definitely yes if no posts are sticky).

**Comment by zdenys** [comment]
6639249-zd-a8c

**Comment by zdenys** [comment]
Thank you for the thorough testing. I had a chance to do my own now and can confirm that my statement was not accurate `the latest Sticky (pinned) posts won't show up in the Blog posts block.`. Instead what you observed is true `The Blog Posts block does seem to ignore sticky status, so it doesn't bump sticky posts up to the top`.

I should have done further testing before posting my report here. My user's case is not related to the original issue above. In their case it's exactly that the Blog Posts block does seem to ignore sticky status entirely. I haven't found the related bug report yet (unless I failed to find it). I can create one or leave it up to you given your thorough test results above. 

It could actually become a feature request for Blog posts block to add a checkbox/toggle to display sticky posts at the top. It can be added somewhere in the block settings.

![yuySkr.png](https://github.com/Automattic/newspack-blocks/assets/39308239/94ad550a-65f6-4c54-943e-07bd6105f39d)

**Comment by cuemarie** [comment]
> It could actually become a feature request for Blog posts block to add a checkbox/toggle to display sticky posts at the top. It can be added somewhere in the block settings.

@zdenys I think this is the right approach! From the OP's original report:

>  'ignore_sticky_posts' seems to be always true (https://github.com/Automattic/newspack-blocks/blob/master/includes/class-newspack-blocks.php#L560) and thus all sticky posts should've been ignore always regardless.

It seems that it's expected that sticky posts are ignored by the Blog Posts block, so a Feature Request would make the most sense!

**Comment by cuemarie** [comment]
> If the blog has sticky posts, the latest sticky post will be missing
> If the blog does not have any sticky posts, the latest post, in general, will be missing

Neither of these behaviors was reproducible during testing.

📌 ACTIONS
- Closed as not reproducible
