### ISSUE TITLE
Post Carousel: Fix AMP validation error

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-blocks#1232]
**Describe the bug**
Newspack Post Carousel block causes AMP validation errors in GSC with this message:  `Usage of the !important CSS qualifier is not allowed.`

**To Reproduce**
1. Add a Post Carousel block to any page. 
3. Run AMP validation. 
4. View message. 

It looks like the AMP tree shaker isn’t able to replace the `!important` qualifiers used here:

https://github.com/Automattic/newspack-blocks/blob/2f09fcfbd150a17408935e99d37c5334120a1c3b/src/blocks/carousel/view.php#L277

**Screenshots**

**Expected behavior**

Pages would pass AMP validation when using the Post Carousel block. 

Edited to add: this has been reported by CalMatters and EastMojo.

**Comment by tmmbecker** [comment]
Enlace reported as well.

**Comment by adekbadek** [comment]
AMP is no longer with us [*]
