### ISSUE TITLE
Donate Block (using WooCommerce and Set Your Own Price) - Indicate minimum donation amount and prevent number counter from going below that amount

### ISSUE THREAD

**Issue by mjonasftc** [Automattic/newspack-blocks#1235]
**Is your feature request related to a problem? Please describe.**
On the WooCommerce-powered donation block, you can set a minimum donation amount for each tier (one-time, monthly, annual) in the WooCommerce product, but there is no UI on the front end that indicates that minimum for the user. Instead, if they try to add an amount below the minimum and then go to the checkout by clicking the donate button, they get a cart error message asking them to fix something. That message also does not give enough information for the end user to actually fix the problem.

**Describe the solution you'd like**
The set your own price option on the donate box should include text indicating the minimum donation amount

It should also prevent the user from entering a number below that minimum.

**Describe alternatives you've considered**
We could also just encourage the admins to add this text using a paragraph block below every donate box, but that seems a little tedious and error prone.

**Comment by dkoo** [comment]
@mjonasftc this should have been fixed by #1239. I'll close this issue for now, but if you see more to do feel free to reopen.
