### ISSUE TITLE
Homepage blocks: Pass attributes to `register_block_type`?

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#14]
Came up during the review of #8 - from @jeffersonrabb:

> I’ve seen some server-side rendered blocks that do pass in the attributes to `register_block_type` ([example](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/latest-comments/index.php#L157-L195)) and some that don’t ( [example](https://github.com/Automattic/jetpack/blob/master/extensions/blocks/tiled-gallery/tiled-gallery.php#L26-L31)). We should assess pros and cons and figure out our policy for this.

Depending on the outcome, this will then need to be updated in the Homepage Article blocks, as well as any other relevant blocks we may be working on.

**Comment by dkoo** [comment]
I think the general policy has been to register attributes server-side if they're needed to render block markup, server-side. There's no real need to register attributes that aren't used (e.g. if the block is a static/non-PHP block).
