### ISSUE TITLE
Homepage blocks: Optimize images

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#15]
This came up in the review of #8, from @claudiulodro:

In that PR, the homepage blocks are always loading the 'large' image size. This doesn't make sense on smaller screens, or when the blocks are displayed in smaller spaces (either because they're in a grid, because they've been scaled down in their own settings, or because they're in a narrow column)

This needs to be improved for optimization; one approach could be srcset, though there may be others.

It also may make sense to include a custom image size in the plugin for this block, rather than relying on a default WordPress one, as they can be changed under Settings > Media Library. We want to be able to count on the image always being a roughly similar size.

**Comment by adekbadek** [comment]
Not relevant anymore, images are optimised.
