### ISSUE TITLE
Columns Block next steps: replace or build our own?

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#151]
The core columns block is falling short of what we need it to do right now:

The way it's structured, with inline styles, makes it tricky to override things.

The default wrapping behaviour is not ideal -- if you leave the columns at their default widths (without setting specific values, or picking one of the layouts where the columns are different widths), they all go to 50% on tablet sized screens. If you have a three-column layout, it means it stacks into two rows, with the final row only taking up half the space. 

This behaivour also means we're running into issues with our border styles, since things wrap kind of unpredictably, and there's no classes on the columns block itself to indicate how many columns it currently has. 

Right now we can work around this by setting specific widths for columns (forcing them to stay like that for tablet-sized screens, and only wrap on mobile). 

For the long term, we should look into replacing this block with another existing block, or, considering how important it is for us to achieve solid layouts, replace it with our own that we have better control over.

**Comment by thomasguillot** [comment]
Related #158 and Automattic/newspack-theme#493

**Comment by thomasguillot** [comment]
Closed via #158 and Automattic/newspack-theme#493
