### ISSUE TITLE
Article Block: Image as background + captions

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#152]
We now have a way to display the featured image behind the article content, as of https://github.com/Automattic/newspack-blocks/pull/73.

However, it clashes with the option to display the image caption in the blocks. 

This issue is to figure out a good approach to this problem -- likely either hiding the option to show the caption if you're displaying the image behind, or figuring out a good placement for it when overlaid on the image.

For the short-term, we can avoid issues by recommending not combining the two settings.

**Comment by thomasguillot** [comment]
We could move the caption to the bottom right of the article?

<img width="1192" alt="Screenshot 2019-10-11 at 17 41 36" src="https://user-images.githubusercontent.com/177929/66669035-8be29f80-ec4e-11e9-8774-583aa8250bc6.png">

**Comment by laurelfulford** [comment]
I like that! 

We might need some kind of fallback/cut off for longer captions (ones that span more than one line) but we can play around with it in implementation.

**Comment by thomasguillot** [comment]
We could use something like `-webkit-line-clamp` and make sure it's only displaying 1 line ([example](https://github.com/Automattic/newspack-blocks/blob/master/src/blocks/carousel/view.scss#L28-L35))
