### ISSUE TITLE
Article Block: Image as background + Vertical spacing

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#153]
https://github.com/Automattic/newspack-blocks/pull/73 Adds a first pass at being able to set the featured image as a background in the article blocks.

Originally the PR included a control for setting the padding on top of the content, so you could adjust the overall width. 

We removed it to simplify things, and to discuss how to best handle this further. 

The problem that needs solving is, generally, you'd want to be able to control "how much" image to show, based on circumstances. However, is there a smart way we can do this automatically depending on where the block is situation/its size? 

Is there a better way to display distance if we have to use a control (percentages, or pixels like the cover block)? 

This issue is to explore and discuss the best next steps.

**Comment by thomasguillot** [comment]
I think we should bring the settings from the Cover Block (Fixed Background, Focal Point Picker) and some from the Hero Block by CoBlocks (Padding, Fullscreen, Height)

<img width="277" alt="Screenshot 2019-10-11 at 17 20 32" src="https://user-images.githubusercontent.com/177929/66668032-3efdc980-ec4c-11e9-87ba-ad6aca8129ec.png">

<img width="277" alt="Screenshot 2019-10-11 at 17 24 27" src="https://user-images.githubusercontent.com/177929/66668113-5ccb2e80-ec4c-11e9-91ae-2132ef728922.png">

**Comment by laurelfulford** [comment]
> I think we should bring the settings from the Cover Block (Fixed Background, Focal Point Picker) 

Focal Point Picker especially would be handy! I think it would need to be a post-level option, though, since the focal point would probably vary from featured image to featured image. Does that make sense? 

> ... and some from the Hero Block by CoBlocks (Padding, Fullscreen, Height) 

I like the use of things like 'huge' for padding :) For the height, do you think the pixels could be be confusing when scaling it down for smaller screens (instead of vague numbers?). Or am I overthinking this :D 

The height/padding question is definitely the bit we need to solve first, to get the option to be more useful. I think these other options would help take it to another level!

**Comment by thomasguillot** [comment]
> Focal Point Picker especially would be handy! I think it would need to be a post-level option, though, since the focal point would probably vary from featured image to featured image. Does that make sense?

Hmm, I didn't think of that... If we display 1 Focal Point Picker per post in the sidebar it might get a bit crowded 😕, unless we can select a post (like a child block) and then the setting appears in the sidebar

> I like the use of things like 'huge' for padding :) For the height, do you think the pixels could be be confusing when scaling it down for smaller screens (instead of vague numbers?)

The Hero Block has 3 settings for the height: desktop, tablet, and mobile. I don't necessarily find it useful though and I much prefer the use of paddings to define the height of a block. It will then scale depending on the content.

But maybe, we could combine the padding option to a "Minimum height in pixel" setting, just like the cover block. And have 3 settings: desktop, tablet, and mobile (and maybe not restrict it to pixel, but also allow rem, em, vh)

**Comment by laurelfulford** [comment]
> Hmm, I didn't think of that... If we display 1 Focal Point Picker per post in the sidebar it might get a bit crowded 😕, unless we can select a post (like a child block) and then the setting appears in the sidebar

I was actually thinking we'd need to have it as an option in each post's editor (though I'm not sure how feesible/not-confusing that would be, either!). If you have a section that just dynamically loads the latest X posts from a category, it'd be really difficult to handle the focal point picking from block. 

This might just be a tough think to include and have it work well in all cases. Having it would be a huge help for one single featured story, it just may not be as helpful when you have a list of stories (in which case we could just recommend picking the centre as the focal point). 

> I don't necessarily find it useful though and I much prefer the use of paddings to define the height of a block. It will then scale depending on the content.

> But maybe, we could combine the padding option to a "Minimum height in pixel" setting, just like the cover block. And have 3 settings: desktop, tablet, and mobile (and maybe not restrict it to pixel, but also allow rem, em, vh)

I like padding as an approach, too. I do think we need some kind of control to change the height in some way, to make this option more usable (right now, it's hard to make out much of the image). I'd be for first adding some kind of control for padding, and then addressing min-height as an enhancement later on. 

@claudiulodro also suggested using the image shape controls for this, which could be a nice more 'broad strokes' kind of approach -- default to having 'some' top padding for the landscape option, increase for square, and max for portrait:

![image](https://user-images.githubusercontent.com/177561/67118879-baa2cd80-f19a-11e9-8aa6-2dc96fa74afe.png)

Right now, switching these image shapes _do_ affect the image used as a background, and they probably shouldn't; but it could instead affect the shape. (If not, they should probably be hidden and not change the image size).

**Comment by dkoo** [comment]
Closing because the "behind" featured image style is now available (which renders the image as a background image with `cover` behavior). Feel free to reopen if more work is needed.
