### ISSUE TITLE
(3P) Article Block: Bring back the more link

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#154]
We originally removed the optional 'More' button from the Article block in #94 because of the block's increasing complexity: the button was added when you could just pick articles by category, and it either linked to that category's archive, or, if you were showing all posts, to the blog posts page. 

As we added more query option (tags, authors, a mix of those plus categories, or a single specific post), it made predicting where the more button should go more complicated.

Charter publications also brought up the fact that the button showed you posts that you likely already saw, and that it would be better if it could somehow offset that, so you would link to articles that you hadn't seen (even if it was just an anchor). 

Ultimately, we decided to remove the button rather than have it there and working illogically. As a short-term fix, the button block is our recommended work-around. 

Despite its removal, the button is still valuable. This issue is to hammer out a good way to bring it back. We may not be able to solve all of the issues above, but as long as we can make sure it's linking to a logical spot, I think that's a solid, helpful start.

**Comment by obenland** [comment]
One other issue that has popped up: we might not always have a blogs page to link to. See https://github.com/Automattic/wp-calypso/issues/36711.

Maybe we could explore the button loading more posts inline, rather than linking out to somewhere else?

**Comment by obenland** [comment]
We could also experiment with post type archive pages in cases where there's no posts page defined.
