### ISSUE TITLE
Blog Posts Block and Post Carousel Block are missing on WordPress.com

### ISSUE THREAD

**Issue by retnonindya** [Automattic/newspack-blocks#1570]
**Describe the bug**
Hello! It seems like the Blog Posts Block and Post Carousel Block (at least these two are the ones I could check) are missing from WordPress.com websites.

**To Reproduce**
1. Go to WordPress.com
2. Create a new page or new post
3. Search for Blog Posts Block or Post Carousel Block
4. Find nothing

(If the block used to exist on the page, the block will error out and gives an error: "Your site does not support the "a8c/blog-posts" block. You can leave this block intact or remove it entirely.")

**Screenshots**
![Screenshot 2023-10-24 at 5 52 49 PM](https://github.com/Automattic/newspack-blocks/assets/44726232/80f6bb62-f8b5-4fce-8a2a-62ebb54de9b6)

![Screenshot 2023-10-24 at 5 55 21 PM](https://github.com/Automattic/newspack-blocks/assets/44726232/d455a774-99d5-44e5-abf5-7eea8d7912e7)

**Expected behavior**
For the Blog Posts Block and Post Carousel to be visible on the editor and working as expected.

**Comment by dolgelukkig** [comment]
7207677-zd

**Comment by retnonindya** [comment]
Fixed. Closing this issue.
