### ISSUE TITLE
Homepage Blocks: Mobile styles

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#16]
Related to the work being done in #8:

The Homepage Article blocks still need mobile styles -- this includes:

- Scaling down appropriately depending on screensize
- Breaking down the 'grid' layout into the appropriate number of columns based on screensize

Also, although not directly related to this block, we also need to consider how things may change when layout blocks -- like Core's Columns blocks -- are used. 

This is related somewhat to work to be done in #15 -- optimizing the image sizes loaded in different circumstances.

**Comment by laurelfulford** [comment]
See #40.

**Comment by dkoo** [comment]
@laurelfulford I'm closing this because Homepage Posts definitely has mobile styles by now, but feel free to reopen if you think more work is needed.
