### ISSUE TITLE
Blog Posts Block offsetting first post

### ISSUE THREAD

**Issue by nazilya06** [Automattic/newspack-blocks#1646]
**Describe the bug**

Hello! It seems like whenever the Blog Posts block is added to the Index/ Home template, it offsets the first post on the live site. However, the post is showing in the Editor.   

**To Reproduce**
1. Go to WordPress.com.
2. Activate any FSE theme. 
3. Go to 'Editor' → Templates → Open Index/Home template
4. Add Blog Posts block.
5. Open the site and see the first post is missing. 

**Screenshots**

**The Editor:**

![Screenshot 2024-01-22 at 13 49 39](https://github.com/Automattic/newspack-blocks/assets/118342580/d84d2cdb-dcd5-4be5-ac54-005d9fea0cad)

**Live Site:**

![Screenshot 2024-01-22 at 13 49 49](https://github.com/Automattic/newspack-blocks/assets/118342580/3661aa69-9438-43b0-9f9d-b6a2f3477609)

**Expected behavior**
The Blog Posts block should display all the posts. 

**Context**

7619465-zd-a8c

**Comment by filipanoscampos** [comment]
This should have been reported in another repo.
Closing as we have the issue https://github.com/Automattic/wp-calypso/issues/69306 as well.
