### ISSUE TITLE
Homepage blocks: Explore scaling options

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#17]
This came up in the review for #8:

Right now, the PR for the homepage blocks includes an option, 'Type Scale', which lets you scale up or down each block:

![image](https://user-images.githubusercontent.com/177561/57794300-308c9f80-76f8-11e9-86c8-4a25e01529da.png)

This allows setting different sets of posts to have different visual importance, but it feels a bit hacky. It would be good to explore other approaches before settling on one (eg. see if this could be rolled into a more streamlined block option approach in #10).

**Comment by dkoo** [comment]
Closing this, but feel free to reopen if still warranted.
