### ISSUE TITLE
Homepage blocks and pagination

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#18]
This came up in the review for #8, from @claudiulodro:

> Any thoughts about how to handle pagination on the homepage? If someone builds a homepage using this, there won't be any link to older articles/page 2.

I did a rough count of some charter members, and some other smaller, and larger, news sites. Of the set 71 I checked, 43 did not have a link to more posts (61%) and 28 did (39%). 

Raising as an issue so we can make a final verdict on it, and the best approach. If we do opt not to add it right now, it's also something we could revisit at any time.

**Comment by jeffersonrabb** [comment]
Duplicating [my comment about this](https://github.com/Automattic/newspack-blocks/pull/8#issuecomment-491812355) just so it's included in the discussion here:

> I'm wondering if pagination is needed at all in this block? In the typical publication homepage use case we're looking at, pagination and infinite scroll aren't really used. The content areas on these pages are typically a fixed number of stories matching a certain criteria, often with a link to an archive page where you can see everything. There might be a separate need for a "paginated list" or "infinite scroll" block for archive pages (or alternate homepage approaches), but I'm not sure we need it here. @laurelfulford does this jibe with your homepage research or am I forgetting a use case?

**Comment by dkoo** [comment]
The Homepage Posts block does have optional "Load more" functionality now, done via JS.
