### ISSUE TITLE
Article Block: Get articles from the sub-categories as well?

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#207]
Original issue by @WPArena here: https://github.com/Automattic/newspack-theme/issues/562:

> Currently, the home page news block is not fetching articles from sub categories. It's just fetching articles from the selected category. I want that it fetch articles from parent and subcategories.

> Can you please fix it?

I think we may want to confirm if this is intuitive to the cohorts as well, and make sure it doesn't cause any unexpected behaviour on live sites.

**Comment by laurelfulford** [comment]
Copying over this description from #313 for this issue (thanks @eduardozulian!)

> **Describe the bug**
> Using the Blog Posts block, I see a not found message if I want to display a parent category but only sub-categories are checked. Similar to #562.
> 
> Let's say I have a travel blog and with this setup:
> 
> * Parent Category: South America
> * Sub-category: Uruguay
> 
> If I don't manually check both South America _and_ Uruguay, I'll see a `Sorry, no posts were found` message.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Make sure you have at least one post under the category Uruguay and that South America (parent category) is not checked
> 2. Add the Blog Posts block
> 3. Select to display posts from a parent category (South America, in my example)
> 4. See error
>
> **Expected behavior**
> To see all the posts under the selected category, even though parent _South America_ was not manually checked.
> 
> This is the expected behavior if I visit `/category/south-america` or filter by category in `wp-admin/edit.php`.
>

**Comment by gamebits** [comment]
TCV has requested this feature.
