### ISSUE TITLE
Query Block: Better discoverability of the child blocks

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-blocks#208]
**Describe the bug**
When I try to add a child block, it's not clear what can I add. I need to go to "Layout Elements" when the available blocks should just be there when I open the inserter (e.g with [Jetpack Contact Info](https://user-images.githubusercontent.com/177929/68661366-c2078d80-0532-11ea-8c09-e077b28d6013.png))

It's also probably worth limiting the type of blocks we can add to just a few:

* Paragraph
* Heading
* List
* Button
* Columns
* Group
* Separator
* Spacer

**To Reproduce**
1. Create a page
2. Add the query block -- You will only have title, date, author -- what else can I add? 

**Screencast**

 
![Nov-12-2019 10-02-41](https://user-images.githubusercontent.com/177929/68662081-0ba4a800-0534-11ea-983b-dfbc1a445dff.gif)

https://cld.wthms.co/zpt43k

**Comment by georgeh** [comment]
I've been poking around the `block-editor` component looking for where this list gets generated, but so far no luck. If we were using `InnerBlocks` we'd be able to pass the `allowedBlocks` prop, but we needed to roll our own implementation with `BlockEditorProvider` and `BlockList`. My best guess is that it's something in the `block-editor` component's store.

**Comment by jeffersonrabb** [comment]
Query block has been relocated to core: https://github.com/WordPress/gutenberg/pull/20106. Closing all Query Block issues in `newspack-blocks` for now, with a possibility of filing them in Core after the block approaches readiness.
