### ISSUE TITLE
Query Block: Editor missing child blocks on page refresh

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-blocks#209]
**Describe the bug**
In the editor, if you add child blocks, then refresh the page, they will disappear and you will only have the original 3 child blocks: title, date, author

**To Reproduce**
1. Create a page with the query block
2. Add different elements, like categories, tags, etc...
3. Save the page
4. Refresh. Do you see the blocks that you previously added?

**Screencast**
![Nov-12-2019 10-11-28](https://user-images.githubusercontent.com/177929/68662639-23c8f700-0535-11ea-92ba-8c2fcd116410.gif)

https://cld.wthms.co/2Ne7CN

**Comment by jeffersonrabb** [comment]
Query block has been relocated to core: https://github.com/WordPress/gutenberg/pull/20106. Closing all Query Block issues in `newspack-blocks` for now, with a possibility of filing them in Core after the block approaches readiness.
