### ISSUE TITLE
Homepage blocks: Additional REST API fields 

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-blocks#21]
After a discussion about using `register_rest_fields` on #8 we decided we should look at the performance implications of the different options.

* Option 1: Use `register_rest_fields`. This option adds additional information to the API responses on the core `post` and `page` routes
* Option 2: Use custom endpoints. This option would add new custom `/newspack/` API routes that would largely mirror the core routes but into which the additional information is built-in and, as we have full control, could be cached more aggressively for better performance.

First we need to assess the performance impact of option 1, which is the current proposal in #8. I.e. does it add new queries? Are those queries repeated on every API request? If so, can we reduce those queries in a performant way?

Second, we need to assess what the relative impact is of using new endpoints? Would the control we get give us enough of a performance benefit to warrant the extra maintenance cost?

**Comment by dkoo** [comment]
#661 deprecated the use of `register_rest_field` in favor of a custom endpoint.
