### ISSUE TITLE
Query Block: Editor doesn't display all the tags

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-blocks#210]
**Describe the bug**
When adding the Tags block, I don't get all the post's tags in the editor but I can see them when visiting the site.

**To Reproduce**
1. Add a page with the query block
2. Add the Tags block. (make sure your posts have more than 1 tag)
3. Notice you only see 1 tag
4. Check the front-end. Do you see all the tags?

**Screenshots**
__Back-end:__

![Screenshot 2019-11-12 at 10 15 54](https://user-images.githubusercontent.com/177929/68662983-c97c6600-0535-11ea-83b1-a45bac94a846.png)

__Front-end:__

![Screenshot 2019-11-12 at 10 17 59](https://user-images.githubusercontent.com/177929/68663009-d5682800-0535-11ea-98f1-ca7e1489fedb.png)

**Expected behavior**

**Comment by jeffersonrabb** [comment]
Query block has been relocated to core: https://github.com/WordPress/gutenberg/pull/20106. Closing all Query Block issues in `newspack-blocks` for now, with a possibility of filing them in Core after the block approaches readiness.
