### ISSUE TITLE
Grunt usage

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/newspack-blocks#219]
I've noticed there is a Gruntfile with some instructions but there is absolutely no documentation on how (and when) to use it. At least I haven't been able to find any: https://github.com/Automattic/newspack-blocks/search?q=grunt&unscoped_q=grunt

Part 2 of the issue: can/should we call the grunt task as part of other tasks in package.json so it gets called as part of the code build or something similar?

**Comment by jeffersonrabb** [comment]
I believe the plugin was originally created using `wp scaffold plugin` and the Grunt files were created then and never used. I can open a PR to remove them unless you'd prefer to have a Grunt workflow as an alternative build process?

**Comment by marekhrabe** [comment]
I'd be for a single build workflow, alternatives make it hard to manage them. I was just wondering if the webpack build covers all the functionality needed if so, let's get rid of the Grunt tasks as they hint towards being required but undocumented (which is what I thought about them)
