### ISSUE TITLE
Homepage blocks: Add ability to adjust excerpt length

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#22]
Right now, the blocks just use whatever the default is for the current site (55 words). It would be great to add a control, so the automatic excerpt could be adjusted by block, depending where in the layout it sits. 

This could be done via a slider with a numeric value field, similar to the number of posts.

**Comment by eduardozulian** [comment]
Got a request in 25453060-hc but looks like it was recently merged on #607 

I am assuming this still needs to be deployed on WordPress.com, right?

**Comment by dkoo** [comment]
This is complete and should be available in WP.com as well
