### ISSUE TITLE
Homepage Blocks: 'View More' link on a per-block basis

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#24]
Many sites include a link from a section of articles on the homepage, to that section's archive.

We could do something similar with the homepage blocks: include an option to have a link to the current category archive.

Out of the box it could have static text ("View More", "View More Articles", "See More"), but we could add an option to edit the text down the road.

One thing to note is that this could become trickier to do with more complex queries (author + tag), since there isn't a default archive page to point to. It's something to look into as we explore this option.

**Comment by laurelfulford** [comment]
The link is added in #37; the link doesn't work in the editor yet; will leave this open until that can get sorted, but it does work on the front-end and can be styled.

**Comment by jeffersonrabb** [comment]
This has been handled in a different way via the dynamic Load More button implemented in https://github.com/Automattic/newspack-blocks/pull/259.
