### ISSUE TITLE
Bring Back Custom Field Block

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-blocks#240]
The custom field  block appears to no longer be available. This is an important step forward from the Homepage Articles block, which doesn't support custom fields such as subtitle.

**Comment by jeffersonrabb** [comment]
Query block has been relocated to core: https://github.com/WordPress/gutenberg/pull/20106. Closing all Query Block issues in `newspack-blocks` for now, with a possibility of filing them in Core after the block approaches readiness.

**Comment by Tanvipatelitp** [comment]
@jeffersonrabb  What about query blocks for newspack?
