### ISSUE TITLE
Query Block: Missing "display as grid"

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#243]
Right now, the Query block is missing the ability to display in multiple columns, and to change the number of columns.

Here are screenshots from the related controls in the Article Block:

![image](https://user-images.githubusercontent.com/177561/70007797-93c01100-1526-11ea-91b9-5592a966968d.png)

![image](https://user-images.githubusercontent.com/177561/70007810-9f133c80-1526-11ea-8dbc-3fb585881c10.png)

**Comment by jeffersonrabb** [comment]
Query block has been relocated to core: https://github.com/WordPress/gutenberg/pull/20106. Closing all Query Block issues in `newspack-blocks` for now, with a possibility of filing them in Core after the block approaches readiness.
