### ISSUE TITLE
Query Block: Featured image missing 'position' options

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#244]
The Featured Image block, inside of the Query block, is missing the ability to set a position.

In the Article block, you can set it to sit on top (default), to the left, right, or behind:

![image](https://user-images.githubusercontent.com/177561/70007859-cc5fea80-1526-11ea-915a-b8e99f7062ed.png)

**Comment by jeffersonrabb** [comment]
Query block has been relocated to core: https://github.com/WordPress/gutenberg/pull/20106. Closing all Query Block issues in `newspack-blocks` for now, with a possibility of filing them in Core after the block approaches readiness.
