### ISSUE TITLE
Query Block: Missing ability to set featured image size

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#245]
The Featured Image block is missing the ability to control its size -- this is currently an option when it's aligned left or right in the article block:

![image](https://user-images.githubusercontent.com/177561/70096617-5a49dd00-15dc-11ea-8dc7-562dde969952.png)

To go with it, there's also an option to stack on mobile:

![image](https://user-images.githubusercontent.com/177561/70096643-633aae80-15dc-11ea-92b6-241972c595f5.png)

(I'm not sure if this one will make sense as is, or if it will be better to set an image size as percentage, relative to the container?)

Related: #244

Edited to update screenshots to match the new control, and add stacking on mobile, a new option.

**Comment by jeffersonrabb** [comment]
Query block has been relocated to core: https://github.com/WordPress/gutenberg/pull/20106. Closing all Query Block issues in `newspack-blocks` for now, with a possibility of filing them in Core after the block approaches readiness.
