### ISSUE TITLE
Query Block: Minimum height option missing

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#246]
In the article block, when you set the featured image to display behind, you also have the ability to set a minimum height:

![image](https://user-images.githubusercontent.com/177561/70011286-bd2d6c80-1527-11ea-81a9-67a1a5bfc90d.png)

In the case of the query block, this might make more sense to implement in a cover-block-like setting (having a container you can apply a featured image background to, to put the query blocks in). 

Related: #244

**Comment by jeffersonrabb** [comment]
Query block has been relocated to core: https://github.com/WordPress/gutenberg/pull/20106. Closing all Query Block issues in `newspack-blocks` for now, with a possibility of filing them in Core after the block approaches readiness.
