### ISSUE TITLE
Query Block: Featured image shape can't be changed

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#247]
The Featured Image block, part of the Query block, doesn't let you set an image size.

The article block currently lets you set the image to be: landscape, portrait, square, or uncropped:

![image](https://user-images.githubusercontent.com/177561/70012504-69bc1e00-1529-11ea-8cc3-91a6a28d6b6b.png)

**Comment by jeffersonrabb** [comment]
Query block has been relocated to core: https://github.com/WordPress/gutenberg/pull/20106. Closing all Query Block issues in `newspack-blocks` for now, with a possibility of filing them in Core after the block approaches readinesss.
