### ISSUE TITLE
NHA: Duplicated avatar on the front-end of the site

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/newspack-blocks#249]
Not sure how I managed to do this, but I see duplicated author avatar on the front-end of the site. @Automattic/ajax 

Tested with the latest zip on an Atomic site. Browser: Chrome, Mac OS.

Front-end:
<img width="1792" alt="Screenshot 2019-12-03 at 13 16 22" src="https://user-images.githubusercontent.com/908665/70054348-4c418f80-15cf-11ea-9ee1-937bfb2504aa.png">

Editor (no duplicated avatar):
<img width="1792" alt="Screenshot 2019-12-03 at 13 17 14" src="https://user-images.githubusercontent.com/908665/70054327-421f9100-15cf-11ea-8d2f-fdeba20c22c8.png">

**Comment by laurelfulford** [comment]
I can recreate this when I have AMP disabled and Jetpack's Lazy Loading images enabled -- if one or the other has a different setting, it won't happen.

The Co-Authors Plus plugin doesn't appear to be having any effect; I'm getting it with and without that enabled.

**Comment by laurelfulford** [comment]
It looks like this is also happening in the theme under the same circumstances, so it's not block-specific: 

https://github.com/Automattic/newspack-theme/issues/617
