### ISSUE TITLE
Query Block: Featured Image - show caption

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#251]
In the Query Block, there isn't an option to display the Featured Image block caption. 

Here is the option in the Article block:

![image](https://user-images.githubusercontent.com/177561/70066500-af1c3200-15a1-11ea-953d-87c8ccb40981.png)

I'm not sure if this would make more sense to handle similar to how it's done in the image block (Rich HTML field that displays the caption, which can then be removed), or if that would be confusing because the caption would only be visible if one of the blocks being previewed had one.

**Comment by jeffersonrabb** [comment]
Query block has been relocated to core: https://github.com/WordPress/gutenberg/pull/20106. Closing all Query Block issues in `newspack-blocks` for now, with a possibility of filing them in Core after the block approaches readinesss.
