### ISSUE TITLE
Query Block: Some kind of type sizing

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#252]
The Query Block is missing the ability to scale up and down the fonts.

In the Article Block, this control affects everything but the 'section header' -- it changes the title, excerpt, date, author, and category:

![image](https://user-images.githubusercontent.com/177561/70066793-22be3f00-15a2-11ea-859e-a4661e50718a.png)

It also affects author avatar size, since it's 'part' of the author markup in the article block, and makes sense to be scaled relative to it to a point. 

It makes it possible to create visual hierarchy when building a homepage.

**Comment by jeffersonrabb** [comment]
Query block has been relocated to core: https://github.com/WordPress/gutenberg/pull/20106. Closing all Query Block issues in `newspack-blocks` for now, with a possibility of filing them in Core after the block approaches readinesss.
