### ISSUE TITLE
Query Block: Custom colours

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#253]
The Query Block currently doesn't let you change the text colours.

Here is the option in the Article block:

![image](https://user-images.githubusercontent.com/177561/70066956-65801700-15a2-11ea-8ddc-3de9e25c60fc.png)

The purpose is to help make sure the text is always legible when the block is nested in a cover or group block with a background colour.

**Comment by jeffersonrabb** [comment]
Query block has been relocated to core: https://github.com/WordPress/gutenberg/pull/20106. Closing all Query Block issues in `newspack-blocks` for now, with a possibility of filing them in Core after the block approaches readinesss.
