### ISSUE TITLE
Feature request: More blocks

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#254]
Moving this issue by @akkiverma over from the theme repo https://github.com/Automattic/newspack-theme/issues/603:

> In the #GFWP meet, it was recommended to use Newspack plugin & theme plus the atomic blocks plugins for extra blocks. I tried atomic blocks for the homepage and it doesn't provide any option to control font size nor they were as good as the one built by Newspack. But the main issue I want to highlight here is since I am on full AMP (for mobile & Desktop both), using atomic blocks costs a lot on the CSS part. It takes a good amount of CSS being added for it and since CSS size is limited in AMP, I want to save as much as I can, hence I uninstalled the plugin.

> So, this is feedback & request, if the newspack can provide more blocks natively, it'll be a great help in staying full AMP for different kind of content & post types.

@akkiverma are there specific blocks you were hoping would be added?

I will also note that any blocks added to Newspack will also increase the CSS load, so this may not resolve the issue you're seeing.

**Comment by akkiverma** [comment]
I've just started using Gutenberg and I am still learning more about it. I tried Atomic Blocks for adding some module on the homepage, but then managed to make it only using newspack blocks. Still exploring more about it at present.

**Comment by laurelfulford** [comment]
I'm going to close this issue for now, since it's not really actionable without specific blocks.

If anyone would like to request a specific block idea to add, we're open to it! Just create a new issue and we'll take a look. Thanks!
