### ISSUE TITLE
Blog Posts Block: "More" button consistence

### ISSUE THREAD

**Issue by retrofox** [Automattic/newspack-blocks#275]
`Continue reading` link and the `More` button look different between the editor and the frontend. Can we make them the same?

**Comment by retrofox** [comment]
Don't forget to enable this feature in the block:

<img src="https://user-images.githubusercontent.com/77539/70625429-5aeffe00-1bf0-11ea-87bd-8dd1b768a866.png" width="400px" />

**Comment by jeffersonrabb** [comment]
The tricky part here is that the frontend button may look different depending on the theme. @thomasguillot what's your opinion on how best to bridge the gap between the two environments?

**Comment by retrofox** [comment]
Are we talking about styling or just the text?
Is the text defined by the styles?

**Comment by retrofox** [comment]
> The tricky part here is that the frontend button may look different depending on the theme

I think it should act as the button block does.

**Comment by thomasguillot** [comment]
> I think it should act as the button block does.
I agree with this.
