### ISSUE TITLE
NHA: Different list of posts on editor and on live site

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/newspack-blocks#280]
**Describe the bug**
It's not possible to list 

**To Reproduce**
1. Add the new Blog Posts/NHA block twice
2. Publish and check the page

**Expected behavior**
I'm not sure if the expected behavior would be to either display the same posts on both blocks (as we see in the editor) _or_ continue the query with only new posts, as I see on the live site.

**Screenshots**

Editor:

<img width="669" alt="Captura de Tela 2019-12-11 às 19 40 02" src="https://user-images.githubusercontent.com/1136160/70666742-0ed3a680-1c4e-11ea-83d4-5882f8e8c242.png">

Live site:

<img width="634" alt="Captura de Tela 2019-12-11 às 19 41 21" src="https://user-images.githubusercontent.com/1136160/70666824-3fb3db80-1c4e-11ea-8b77-cf4aaf8f4a2b.png">

**Comment by jeffersonrabb** [comment]
Previous discussion can be found in `CJS75TX3R/p1575553314253500-slack-ajax` and `paYJgx-jW-p2`, and work in https://github.com/Automattic/newspack-blocks/pull/176 is directly relevant.

**Comment by jeffersonrabb** [comment]
This is resolved in https://github.com/Automattic/newspack-blocks/pull/289 (although note this change isn't synced to WP.com yet)
