### ISSUE TITLE
Blog Posts Block: iFrame Embeds not displaying.

### ISSUE THREAD

**Issue by ersatzpenguin** [Automattic/newspack-blocks#299]
**Describe the bug**
When using the Blog Posts Block, setting it to display a post that contains an iframe results in the iframe being stripped, and its contents being displayed as text instead.

**To Reproduce**
1. Publish a post with an iframe embed.
2. Add the Blog Posts Block to a page, and ensure it's set to display the post with the iframe.
3. View the page with the Blog Posts Block live.
4. See error.

**Screenshots**
Post with an iframe embed:
![image](https://user-images.githubusercontent.com/10101587/71031884-e62e2f80-20d9-11ea-9d4d-1d28ffd5ceb2.png)

Same post displayed in a Blog Posts Block: 
![image](https://user-images.githubusercontent.com/10101587/71031767-a49d8480-20d9-11ea-8ea6-6813e7d01c9a.png)

**Expected behavior**
When using the Blog Posts Block, I expected it to behave essentially the same way that a vanilla post/archive page would—displaying the content of posts including any embeds etc.

This specifically came up in 2568451-zen

**Comment by laurelfulford** [comment]
Thanks for reporting this, @ersatzpenguin! 

Looking at the site in question, it looks like it's using the older

**Comment by ersatzpenguin** [comment]
Thanks! I didn't catch that! I was so excited to see the Blog Posts Block come through that I assumed that was what I was seeing. :).

**Comment by laurelfulford** [comment]
No worries! There's a _lot_ of overlap between the two, I imagine this is going to be confusing for the next little while :)

**Comment by laurelfulford** [comment]
We've had a second ask for an option to show full content of a post; I was sure it was a duplicate, but I couldn't find this issue because I didn't think to rename it, even though I left it open as a feature request for full content! 

So I'm going to close this one in deference to #385 as it's more specific about that feature, to save me from getting confused in the future!
