### ISSUE TITLE
Split Up Display Settings 

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-blocks#301]
This was first suggested by @thomasguillot [here](https://github.com/Automattic/newspack-blocks/pull/297#issuecomment-566605904). 

Consider splitting `Display Settings` panel into multiple panels for better organization:

![](https://user-images.githubusercontent.com/177929/71011997-47f49680-20e6-11ea-91a8-8d4bbca8fae2.png)

**Comment by dkoo** [comment]
No longer relevant; this is now how the sidebar is organized.
