### ISSUE TITLE
Donate block: Change default option

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-blocks#303]
With the reader able to choose between monthly, annual and one-time donations, it would be good to allow the publisher to change the default to encourage a particular choice.

This could be done in the block settings, for example.

**Comment by joeboydston** [comment]
Also requested by Daily Yonder:

> We’ve been messaging around it, but have still gotten some harsh emails and lost some goodwill with a few donors. One of our editors is growing frustrated with it and says he wants to move us to another donation plugin if we can’t get it resolved.
