### ISSUE TITLE
Blog Posts Block: Wide and Full Width settings ignored

### ISSUE THREAD

**Issue by MindyPostoff** [Automattic/newspack-blocks#304]
When a Blog Posts Block is added to the content, there is a setting for the width of the block to be Wide or Full-Width. Neither of those seem to work on the front end, despite the editor showing the width change.

**To Reproduce**

1. Create or edit a page.
2. Add the Blog Posts Block and display posts as a grid of at least 2 columns.
3. Change the width setting to be either Wide or Full-Width and publish/update the page
4. View the front end of the page and notice that the width of the posts grid is confined by the max-width of the theme's content area.

**Screencast**

https://d.pr/v/RioQYJ/teJ3XmVq8n

**Expected behavior**

When the Blog Posts Block is set to be Wide width, for the grid to be displayed wider than the default content width of the theme, and when set to be Full-Width, for the grid to display the full width of the page.

**Comment by michaeldcain** [comment]
@obenland: this seems to be related to the empty div wrapper for the block. The alignment class name is applied one level below, and thus, the wrong styles are applied:

<img width="637" alt="Screen Shot 2019-12-19 at 10 45 07 AM" src="https://user-images.githubusercontent.com/942359/71187241-afc4f180-224c-11ea-881f-f1a1ad396308.png">

**Comment by jeffersonrabb** [comment]
This was resolved in https://github.com/Automattic/newspack-blocks/pull/282, but the version on DOTCOM hasn't been synced since the fix.

**Comment by jeffersonrabb** [comment]
DOTCOM was just synced, this should now be live.

**Comment by MindyPostoff** [comment]
@jeffersonrabb Do you know if that also means it's been synced with atomic sites? Or is that a separate process?

**Comment by jeffersonrabb** [comment]
@MindyPostoff I just updated the plugin on .org (https://wordpress.org/plugins/full-site-editing/) so it should be updating on Atomic sites shortly.
