### ISSUE TITLE
Blog Posts Block: Columns setting controlled by number of published posts

### ISSUE THREAD

**Issue by MindyPostoff** [Automattic/newspack-blocks#305]
When adding a Blog Posts Block, the number of columns is restrained by the number of blog published posts there are on the site. For example, if someone wants to display their posts in 3 columns, but only has 1 published post when starting, the number of columns setting does not allow them to make that change. It seems like there has to be at least the number of published posts as desired columns to make that setting save.

**To Reproduce**

1. Count how many published posts there are on the site.
2. Create or edit a page.
3. Add the Blog Posts Block, set the display to be grid (not list), and change the columns setting to be more than the number of published posts.
4. Move the focus away from the columns setting field or publish/update the page and notice that the value entered is not saved.

**Screencast**

https://d.pr/v/4IlXIK/FoEr4COhEX

**Expected behavior**

For the columns value to be saved and respected, regardless of how many published posts there are.

**Comment by laurelfulford** [comment]
Related to #92.
