### ISSUE TITLE
Blog Posts Block: Add tooltip instructions

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/newspack-blocks#310]
**Is your feature request related to a problem? Please describe.**
Between myself and a user, we didn't find that the Choose specific stories feature was intuitive that you had to use post titles and that IDs wouldn't work. We thought it was a bug.

**Describe the solution you'd like**
If allowing post IDs to also work isn't reasonable, perhaps we could add a tooltip that would provide instructions to the user that they need to type post titles to choose specific posts.

User report: #2579306-zen

**Comment by thebud15** [comment]
Just noting that the same user suggested changing the wording in the sidebar to "stories" instead of "posts". Was there a reason we chose that terminology? (I'm assuming as it's Newspack-centric, but I figured I'd mention it).

**Comment by jeffersonrabb** [comment]
> Just noting that the same user suggested changing the wording in the sidebar to "Posts" instead of "Stories".

Absolutely correct, this is an oversight! @thebud15 would you open an issue for that correction?
