### ISSUE TITLE
Blog Posts Block: "No posts were found" in parent category

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/newspack-blocks#313]
**Describe the bug**
Using the Blog Posts block, I see a not found message if I want to display a parent category but only sub-categories are checked. Similar to #562.

Let's say I have a travel blog and with this setup:

* Parent Category: South America
* Sub-category: Uruguay

If I don't manually check both South America _and_ Uruguay, I'll see a `Sorry, no posts were found` message.

**To Reproduce**
1. Make sure you have at least one post under the category Uruguay and that South America (parent category) is not checked
2. Add the Blog Posts block
2. Select to display posts from a parent category (South America, in my example)
3. See error

**Expected behavior**
To see all the posts under the selected category, even though parent _South America_ was not manually checked.

This is the expected behavior if I visit `/category/south-america` or filter by category in `wp-admin/edit.php`.

**Comment by laurelfulford** [comment]
Thanks for filing this issue, @eduardozulian! This sounds similar to #207, so I'm going to close it as a duplicate, but copy over your description there, as it walks through the issue really nicely.

I'm not sure what #562 should link to -- maybe a separate repo, or a typo for an issue in this one? In either case, please add any additional info to #207 if you think it'll help. Thank you!
