### ISSUE TITLE
Blog Posts Block: Selecting Author in block settings is not working

### ISSUE THREAD

**Issue by ajaykj** [Automattic/newspack-blocks#318]
On a multi-author blog adding the `Blog Posts` block in a page and then choosing an author under `Authors` under the block settings is having no effect on the content of the block. The selected author disappears as soon as `Comma` or `Enter` key is pressed.

**Steps to reproduce the behavior:**
1. Go to 'https://wordpress.com/pages/' or `https://wordpress.com/posts/`
2. Click on 'Add New Page' or 'Add New Post'
3. Search and add `Blog Posts` block
4. In the Block settings > Authors add an author(s) name followed by a comma or the Enter key.

**Expected behavior**
The blog should list the posts by that particular author only.

**What happens**
All the blog posts are listed. The Author name disappears from block settings.

**Screenshots**

https://d.pr/i/uMRqbr

**Comment by jeffersonrabb** [comment]
The Authors field (as well as Categories and Tags) is a tokenized autocomplete field, where typing the name of an author reveals a list of possible matches, and when a match is clicked that author is added as token. The helper text ("Separate with commas or the enter key.") is misleading and was removed in https://github.com/Automattic/newspack-blocks/pull/316 (although has not yet been synced to WP.com). These screenshots show how the flow is supposed to work, which will be on WP.com shortly:

<img width="277" alt="1" src="https://user-images.githubusercontent.com/1477002/74887175-39c23100-5348-11ea-8c68-2e59c20b12c9.png">
<img width="274" alt="2" src="https://user-images.githubusercontent.com/1477002/74887174-39c23100-5348-11ea-9867-ce16a66ccf6b.png">
<img width="274" alt="3" src="https://user-images.githubusercontent.com/1477002/74887173-39299a80-5348-11ea-949a-44ce80d69cfe.png">
