### ISSUE TITLE
Columns Block: `calc()` is stripped out of inline styles when user doesn't have `unfiltered_html`

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#321]
In the block, we've reworked the Columns Block to use `calc()` in the inline CSS, as a temporary work-around for a bug.

However, if a user doesn't have `unfiltered_html` ability (anyone but Administrators), the `calc()` style is stripped out, causing the block to throw an error. This has to do with this safe CSS filter here: 

https://developer.wordpress.org/reference/functions/safecss_filter_attr/

... and only happens when you change the widths of the columns (eg. when they are all not the same width as each other). 

One work-around may be to change the columns block to use negative margins on the outside, and use margins/padding to add the gutters for the block, rather than using `calc()` to make each column narrower. A change like this will require existing column blocks to be updated as well, as they'll start throwing errors in the editor as soon as the expected `calc()` value is removed.

There also may be something we can do about the validation for the short-term. 

Related Core issue: https://core.trac.wordpress.org/ticket/46197

**Comment by claudiulodro** [comment]
Something like this snippet would solve the problem in theory, but it's pretty dangerous and hacky IMO:

```
add_filter( 'safe_style_css', function( $css ) {
	if ( stripos( 'calc(', $css ) ) {
		return [];
	}

	return $css;
} );
```
