### ISSUE TITLE
Homepage Structured Data Showing an hentry Markup

### ISSUE THREAD

**Issue by SanjayKumarMonu** [Automattic/newspack-blocks#323]
Hi Automattic Team,

This is Sanjay congratulating you for building such an awesome theme. Well, there are a lot of features I like about the Newspack theme and Newspack Block Plugin is one among them. The primary reason is it provides us a variety of custom blocks which we can use to design our pages.

I use the Newspack Block Plugin to customize the Homepage of one of my website. However, One issue I encountered and that is related with the Structured Data markup. While using Newspack Block Plugin to insert blocks on my website homepage I found that it insert a hentry markup for one article of the block present at the top.

I am also using Yoast SEO Plugin to manages internal SEO of my site and I also checked the same issue by deactivating the Yoast SEO plugin and it remains there. Well, the structured data markup isn't showing an error but giving an hentry markup on the homepage.

Could you please take a look into that?

With Regards,
Sanjay

**Comment by adekbadek** [comment]
Hi @SanjayKumarMonu,

Could you please share precise steps to reproduce the issue? Specifically, I'm having trouble understanding this part:

> I found that it insert a hentry markup for one article of the block present at the top.

What is hentry markup?

**Comment by adekbadek** [comment]
Closing due to lack of response.
