### ISSUE TITLE
UI Quirks Since Gutenberg 7.2

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-blocks#329]
**Describe the bug**
Since the release of Gutenberg 7.2, a few minor UI issues have popped up.

1) The content of `Placeholder` elements seems to be left-aligned, while it was previously centered:

![Screen Shot 2020-01-12 at 8 03 08 PM](https://user-images.githubusercontent.com/1477002/72228771-9a0ac980-3577-11ea-93c0-55db0882ecf0.png)

![Screen Shot 2020-01-12 at 8 11 08 PM](https://user-images.githubusercontent.com/1477002/72228784-b149b700-3577-11ea-8055-4e07bd07c1c2.png)

2) In the `FormTokenField` component the UI for each token is too tall. This affects the block because of the Categories, Authors, Tags, and Specific Posts fields. However, the issue appear to affect normal Category UI on Posts, as well.

![Screen Shot 2020-01-12 at 8 03 36 PM](https://user-images.githubusercontent.com/1477002/72228847-48167380-3578-11ea-8a7c-4f5221b4dcbf.png)

![Screen Shot 2020-01-12 at 8 12 55 PM](https://user-images.githubusercontent.com/1477002/72228849-4ba9fa80-3578-11ea-9b6f-01cbb6ed7619.png)
 
**To Reproduce**
1. Install the latest Gutenberg plugin (7.2)
2. Edit a page or post with the Homepage Posts block. Observe the left-alignment of the Spinner and "No Posts" messaging.
3. View the Inspector Controls for the block. Add a category, tag, or author. Observe the additional vertical space.

**Comment by thomasguillot** [comment]
A few notes:

The left-align new behaviour of the Placeholder is not a bug, see https://github.com/WordPress/gutenberg/pull/18745

That being said, the Spinner, on its own looks a bit odd when left-aligned so #348 should take care of it.

`FormTokenField` looks fine in Gutenberg 7.3.0.

**Comment by jeffersonrabb** [comment]
Resolved in https://github.com/Automattic/newspack-blocks/pull/348
