### ISSUE TITLE
Multiple Premium Themes: JS error on IE 11 causes site to load blank or breaks the mobile menu toggle

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/newspack-blocks#332]
We have received multiple reports from happiness engineers about premium themes and IE11.

The following themes are loading broken or blank, with this error in the console log:

`Object doesn't support property or method 'forEach'`

Broken themes:
* Solar
* Huntt
* Goodz Magazine
* Ippo
* Eris
* Aperitive
* Veni

Same error but broken mobile menu toggle:
* Adaline
* Owari
* Vivaro
* Spatial
* Bari
* Novara

The theme shops pointed out that the issue is on our end.

Looks like the corresponding WordPress.com code can be found here: ​https://github.com/Automattic/wp-calypso/blob/fe44257b9e3bbf6aff1692ef5601eda1d7588d4d/apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/view.js#L18

They said that, it appears to be an easy fix, just have to add a polyfill: ​https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Browser_Compatibility

**Comment by danieldudzic** [comment]
cc: @obenland

**Comment by obenland** [comment]
Yes, looks like we need to be a bit more verbose in our handling of empty results from `querySelectorAll`. See the last example here: https://developer.mozilla.org/en-US/docs/Web/API/NodeList#Example

Something like this maybe?
```js
Array.prototype.forEach.call( document.querySelectorAll( '[data-load-more-btn]' ), attachLoadMoreHandler );
```

**Comment by jeffersonrabb** [comment]
Discussion here: https://github.com/Automattic/newspack-blocks/pull/259#discussion_r354398108. @marekhrabe had wanted to avoid polyfilling globals (https://github.com/Automattic/newspack-blocks/pull/259#discussion_r354446412) but I'm not sure we ever established a preferred approach?

**Comment by obenland** [comment]
It's a little disappointing that we knew about the issue beforehand, had a fix in place, and then shipped without it.

@marekhrabe How do you feel about the non-polyfill fix suggested in https://github.com/Automattic/newspack-blocks/issues/332#issuecomment-573791188?

**Comment by poojashetty18** [comment]
I found a similar issue with the Arcade theme where the header image is breaking on IE 11.

Screenshot of example site: https://jcumuscom.files.wordpress.com/2020/01/internet-explorer11.jpg

Screenshot of theme: https://jcumuscom.files.wordpress.com/2020/01/20200107_125030.jpg

**Comment by danieldudzic** [comment]
Hey @obenland,

This fix has been deployed already, right?

Dotcom sites are still experiencing issues. Is there some way we clear the cache and have the updated version load?

**Comment by obenland** [comment]
It has not been deployed. I’d expect it to ship next week, together with other fixes

**Comment by danieldudzic** [comment]
Hey @obenland - I can't find info whether this has been deployed already or not.

Dotcom sites are still experiencing the `Object doesn't support property or method 'forEach'` issue.

**Comment by obenland** [comment]
I'm sorry that this has been taking so long to get on dotcom. It's been repeatedly pushed back to incorporate more changes that had been in progress. We finished those up yesterday and with the .26 version bump these will finally be deployed.
