### ISSUE TITLE
Homepage Posts: Add classes for posts categories and tags

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#363]
In WordPress, on single posts, CSS classes can be added for each of the tags and categories applied to the post, using `<?php post_class(); ?>`. It would be very handy to do something similar to the `<article>` classes in the Homepage Posts block, because then they could be used to add custom styles to specific tags/categories. 

Edited to add: one good use case for this is a 'Sponsored' or similar tag or category, to do something to make it clear that these posts are different.

**Comment by claudiulodro** [comment]
Would the Additional CSS Classes setting for the block work? e.g. just set `sponsored` as an additional class.

**Comment by laurelfulford** [comment]
It'll work for a whole block, but it's unfortunately not possible to add to a single post unless the block is nothing but the one post. Which is a way around it too -- this could just be a bit less manual, and lets these posts be mixed in with others a bit easier :)
