### ISSUE TITLE
Article Carousel: Author not appearing in editor

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#370]
When using the Article Carousel block, the author and author avatar do not appear in the editor preview:

![image](https://user-images.githubusercontent.com/177561/74486203-48ed3e80-4e71-11ea-9031-531da5b07cad.png)

They do display as expected on the published page, though.

**Comment by jeffersonrabb** [comment]
Duplicate of https://github.com/Automattic/newspack-blocks/issues/445
