### ISSUE TITLE
Article Carousel: does not filter out posts w/ featured image in the editor

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-blocks#380]
**Describe the bug**

In the editor, the articles carousel may show this empty state if none of the articles in the carousel has a featured image:

![image](https://user-images.githubusercontent.com/7383192/75044575-2aff8980-54c2-11ea-88b5-5ccced363b9c.png)

**To Reproduce**
1. Create 3 posts without featured image
1. Insert an Articles Carousel block

**Expected behavior**

Should display only posts with featured image, like the carousel that is rendered on the front-end.

**Comment by jeffersonrabb** [comment]
I believe you're describing the issue resolved in https://github.com/Automattic/newspack-blocks/pull/440? If I'm misunderstanding, please reopen.
