### ISSUE TITLE
Blog Posts Block Conflicts with Content Options Setting for Pages

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/newspack-blocks#389]
**Describe the bug**
When you add the blog posts block and posts have featured images, the images won't show on that block if the setting to show featured images on pages is off in Customize - Content Options.

**To Reproduce**
1. Go to https://wordpress.com/block-editor/page
2. Add the blog posts block to a page: 
<img width="892" alt="Screen Shot 2020-03-01 at 6 02 51 PM" src="https://user-images.githubusercontent.com/25575134/75635795-e2914b80-5be6-11ea-8cdd-ea5841064f69.png">

3. Make sure that a few of your recent posts have featured images. 
4. Go to Customize -> Content Options and disable the featured images to show on pages:

<img width="1004" alt="Screen Shot 2020-03-01 at 6 04 05 PM" src="https://user-images.githubusercontent.com/25575134/75635812-13718080-5be7-11ea-807d-280f525299b3.png">

5. Check the blog posts block embedded into the page

**Expected behavior**
I expected the featured images for posts to stay 

<img width="863" alt="Screen Shot 2020-03-01 at 6 05 46 PM" src="https://user-images.githubusercontent.com/25575134/75635830-4a479680-5be7-11ea-89bb-d73ef43af6e3.png">

**What happened**
The setting from Customizer also affected the blog posts block and the images were gone:

<img width="899" alt="Screen Shot 2020-03-01 at 6 06 16 PM" src="https://user-images.githubusercontent.com/25575134/75635866-a4e0f280-5be7-11ea-8767-177259e8db4e.png">

Tested with a few themes such as Ixion and Harmonic.

**Comment by damiannep** [comment]
Same issue as in https://github.com/Automattic/newspack-blocks/issues/399
