### ISSUE TITLE
Blog Posts Block: Weird distribution of grid items

### ISSUE THREAD

**Issue by alaczek** [Automattic/newspack-blocks#396]
#### Steps to reproduce
1. Test on a site with 5 blog posts.
2. Add the Blog Posts block to a page. Set the posts to display as a grid, 3 per row, display 6 posts at a time.
3. Notice how in the second row the last post is aligned to the right, leaving big gap in the middle.
4. Tested with Maywood, TwentyTwenty, Independent Publisher 2.

#### What I expected
I expected that if there weren't enough posts to fill the grid, the big gap would be at the bottom right.

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/4550351/73236158-7ab1a480-41e5-11ea-990b-5763c315a4f1.png)

#dogfooding

**Comment by dromero20** [comment]
We had a report today regarding this on https://returnloveorganization.com/blog

They're using the Blog Posts block with Grid View. In Desktop, posts are aligned correctly:

<img width="1175" alt="Captura de pantalla 2020-06-04 a las 10 33 18" src="https://user-images.githubusercontent.com/23258551/83734136-e225a800-a64e-11ea-9406-27495f54ec9e.png">

But using a tablet, the two last ones are not aligned:

<img width="784" alt="Captura de pantalla 2020-06-04 a las 10 33 36" src="https://user-images.githubusercontent.com/23258551/83734192-f36eb480-a64e-11ea-9323-20ca1861b6a9.png">

We fixed this out by using this CSS code

```
@media only screen and (min-width: 600px) {
.wpnbha.columns-3 article, 
.wpnbha.columns-6 article {
    margin-bottom: 1em;
}
}
```

But ideally, this should be reviewed.

Reported in #21637853-hc

**Comment by laurelfulford** [comment]
Hey @dromero20! That issue actually sounds like this one: 

https://github.com/Automattic/newspack-blocks/issues/482

The spacing styles in the block specific, overriding what the theme was doing.

There is a fix, it will be added to WP.com the next time the block is synced; in the meantime, I'm going to add your report there, and switch this issue back to an enhancement :)

**Comment by tanjoymor** [comment]
Had another case of this here: 28397782-hc and followed up here: 3845612-zd with the follow CSS workaround:

```
body .wpnbha.is-grid>div {
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-start;
    padding: 0;
    list-style: none;
}

@media only screen and (min-width: 782px){
.wpnbha.is-style-borders.is-grid article {
    padding-left: 20px;
}
}
```

**Comment by laurelfulford** [comment]
Looks like a duplicate issue for this was filed and fixed -- closing! 

https://github.com/Automattic/newspack-blocks/issues/1171
