### ISSUE TITLE
Homepage mobile ordering

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#40]
This came up during the community meeting:

How should the homepage block layouts break down on small screens?

Out of the gate, it will break down left to right, into one column -- so stories on the left will be on the top, stories in the middle will be next, and stories on the right will be at the bottom. 

If the most important story is in the center, it will end up further down the page on small screens, which isn't desirable. 

Is there a way to set a priority of the stories, so the most important can be in the center on desktop, and at the top on mobile? And is there a way to do this that the source order reflects the visual order (so it remains accessible/easy to tab through without having to do some weird fancy footwork). 

(This largely involves the core Columns block, rather than the homepage blocks, since the latter is used for creating the different hierachy). 

Edited to add: the Vox homepage shows an example of this: https://www.vox.com/ The center story is the focus, and when you shrink down the browser window it's at the top. It's also first in the HTML order, which means in the tab order, it's the first thing you get to after the header.

**Comment by laurelfulford** [comment]
I had a quick chat with @davidakennedy to get a better understanding of the a11y impact of something like this, since it seemed like the biggest potential issue. I was worried about having the articles display in a different order, visually, than they would be in the tab/source order. 

He said this should be fine in this case, looking at the [Vox](https://www.vox.com/) example. Those centre stories are, visually and page hierachy-wise, the most important thing on the page. So for them to come first for a screen reader, while tabbing, or on mobile makes the most sense. 

**Desktop:**

![image](https://user-images.githubusercontent.com/177561/60616885-54c73d00-9d87-11e9-9d47-7606436e82d6.png)

**Mobile:**
![image](https://user-images.githubusercontent.com/177561/60616917-6577b300-9d87-11e9-8f58-811f0f02a60d.png)

A good parallel would be of a site that had a header, a primary content area, and a secondary content area (sidebar). With a logical source order, this page would go header, primary content and secondary content, even if, on desktop, you opted to display that sidebar on the left (so reading ltr, it would be 'first'), because the secondary content is visually/hierarchically the least important.

![image](https://user-images.githubusercontent.com/177561/60617046-ac65a880-9d87-11e9-8ba9-3f6ba6b99b9c.png)

So: this approach won't be problematic, as long as those center stories are visually/hierarchy the most important. 

I think, too, it's something that would ideally be limited to the first section of the page, to reduce complexity. I imagine it could be something like picking the 'focus' column in a block, though I'm not 100% sure how we would pull that off/what would need to happen underneath the hood. 

As a hacky starting point, we could create some Advanced CSS classes, or Block styles, that moved the first column to the second, third, fourth... spot. So someone would need to place their most important stories in the first column, since they need to appear first, but then visually move that column to the centre/end using CSS/flexbox.

**Comment by dkoo** [comment]
The Columns block now has the ability to visually re-order its columns, so closing. Feel free to reopen if more is needed on this.
