### ISSUE TITLE
Blog Posts Block: Date Being Hidden by Themes

### ISSUE THREAD

**Issue by Aurorum** [Automattic/newspack-blocks#405]
**Describe the bug**
The majority of themes hide the `updated` class, although I'm unsure of the conditions on which this is added: https://github.com/Automattic/themes/search?l=CSS&q=.byline%2C+.updated
 
This causes the Homepage Articles date not to work

**To Reproduce**
1. Activate a free WordPress.com theme
2. Add the block and select showing the date
3. Verify if this class is applied
4. See issue

**Screenshots**
<img width="591" alt="Screenshot 2020-03-11 at 17 11 01" src="https://user-images.githubusercontent.com/43215253/76444065-4ec83800-63bb-11ea-9c25-d469715343fb.png">

**Expected behavior**
Both blocks should display the date.

**Comment by laurelfulford** [comment]
Hey @Aurorum!

Some themes output both an original published date and an updated date for posts you've edited more than once.

So when you publish a post, it will have both the classes `published updated` on one `time` tag, but when you update a post, it will still have the original `time` tag with the `published` class, plus a second `time` tag with an `updated` class that's hidden. 

I tried recreating this issue with three free themes on WP.com that appear in your linked search results, but could not recreate this -- with a mix of one-time published posts and posts I've edited, they all show the date. Can you share exactly what theme you're using in the screenshot, and any other details you think may help? (like do the dates appear when you set the author to display?)

Thanks!

**Comment by Aurorum** [comment]
Hmm, good point; it appears that the link I referenced doesn't necessarily have an impact on the date being hidden. I definitely can recreate this with the Harmonic theme though, and #406 does fix it there, and setting the author to display has no impact.
