### ISSUE TITLE
Blog Posts Block: Load More Button Displays All Posts Even When Specific Category Selected

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/newspack-blocks#411]
**Describe the bug**
When adding a Blog Posts block to a page, you can select a category to have it display, and have a show more button displayed as well. However, when you click the Show More button, posts from all categories are shown instead.

**To Reproduce**
1. Add a Blog Posts block to a post or page.
2. Set it to display posts from a specific category.
3. Enable the "Show More Button" option.
4. Publish the post/page

**Screenshots**
![Screen Shot 2020-03-16 at 16 00 12](https://user-images.githubusercontent.com/42454301/76795335-4c8d2180-679f-11ea-9ab6-15135c4b6fda.png)
<img width="815" alt="Screen Shot 2020-03-16 at 16 01 54" src="https://user-images.githubusercontent.com/42454301/76795415-7cd4c000-679f-11ea-9ce5-31f5854748d5.png">

**Expected behavior**
When clicking the Load/Show More button, only posts from the selected category should be shown.

User mentioned the bug here: 2791744-zen

**Comment by mriyazuddin** [comment]
User in #2791744-zen has reported that the issue still persists. I have also verified that on their website.

**Comment by jeffersonrabb** [comment]
> User in #2791744-zen has reported that the issue still persists. I have also verified that on their website.

This is due to delay between issue resolution in `newspack-blocks` and synchronization to FSE plugin, and deployment on WP.com. We're going to need a way to track the synchronization cycle so that HEs and others can follow the status of issues like these. @obenland @noahtallen @retrofox  any thoughts on how we might do this?

**Comment by noahtallen** [comment]
You're spot on about the matter. First, I have this PR (which now needs to get the newer version) to update it on dotcom, but it has not been reviewed yet: https://github.com/Automattic/wp-calypso/pull/40144.

Second, [wp-calypso/apps/full-site-editing/package.json](https://github.com/Automattic/wp-calypso/blob/d9c648cc68d8d0d879f6b82349a25e864ff473c8/apps/full-site-editing/package.json#L81) always contains the latest version of the block loaded in the FSE plugin. There is a slight gap between that being updated and it being available publicly, but it every conversation I've seen points to it simply not being updated at all on dotcom yet.

Currently, it's done ad-hock, which as we can tell isn't working. ;) Now that our division has a specific maintenance squad, what if we add this update task to the list of other things the squad has to update (Gutenberg, Coblocks, etc)? I think it might informally be on that list, but as the squad gets going, it should become more regular.

**Comment by galakhyati** [comment]
@noahtallen As per the PR, I see it is merged now, I checked on the user's site right now and see the issue still persists. 

I am assuming the ad-hock fix still needs some fixing even after the PR fix, yes?

**Comment by noahtallen** [comment]
> I am assuming the ad-hock fix still needs some fixing even after the PR fix, yes?

The change has been merged but not deployed yet. Once the FSE plugin has been deployed, then the change will be live on wpcom. :) This is the other gap of the release process, where the change is ready to be deployed, but not deployed yet!

You can definitely expect it to be deployed in the upcoming week. It will probably happen around the time we update Gutenberg 7.7.1. I'll respond on this post when it's released!

**Comment by noahtallen** [comment]
@galakhyati @jeffersonrabb v1.2 of the newspack posts block is now running on all simple and Atomic sites, so the issue should now be resolved.
