### ISSUE TITLE
Homepage blocks: Ordering articles

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#42]
Right now, articles only appear in reverse chronological order. 

We should look at adding other options -- one that specifically came up was the ability to craft a specific order, when paired with picking specific articles to appear in a block (see #41).

It may also be good to include other standard WordPress query orders, like chronological.

**Comment by laurelfulford** [comment]
> one that specifically came up was the ability to craft a specific order, when paired with picking specific articles to appear in a block

A hacky way to do this would be, if it was possible to pick a specific article to show in this block, to combine separate blocks together, each with a different article, so you could use Gutenberg's regular ordering to order the articles.

**Comment by adekbadek** [comment]
Additionally proposed ordering options in https://github.com/Automattic/wp-calypso/issues/40397:

> These options should be available:
> 
> Newest to Oldest (default)
> Oldest to Newest
> Alphabetical A to Z
> Alphabetical Z to A

**Comment by AtrumGeost** [comment]
Got a user asking for this feature here:

31180470-hc

**Comment by laurelfulford** [comment]
#509 is the same issue; it's a newer duplicate, but it has more comments so I'm going to close in favour of that one and copy these comments over there so we don't lose track of them!
