### ISSUE TITLE
Group Block: Align left and right styles broken in editor

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#433]
The align left and align right styles we added to the Group Block are badly broken in the editor preview:

![image](https://user-images.githubusercontent.com/177561/80010603-81b42000-847f-11ea-803e-5e6d19e1c8a7.png)

**Comment by jeffersonrabb** [comment]
Curious what your Gutenberg version is?

**Comment by laurelfulford** [comment]
I'm using 7.9.1, but could recreate with 7.9 -- it's fine in 7.8.1.

I think it's similar to what's causing #434, and causing issues with our custom typography/colours from the theme previewing in the editor too 😐 

For the group, it looks like the editor no longer included the class `.block-editor-block-list__layout` -- it's used here:

https://github.com/Automattic/newspack-blocks/blob/e24bf8c4a15816c4885b4a0a35424b726c04b425/src/block-styles/core/group/editor.scss#L1

... that also looks like the issue with the type/colours. For the Columns, I'll have to do a bit more digging but it looks like it might related to `.wp-block` class being on the same element as `.wp-block-columns`, and not a parent, like it is in the styles:

https://github.com/Automattic/newspack-blocks/blob/e24bf8c4a15816c4885b4a0a35424b726c04b425/src/block-styles/core/columns/editor.scss#L4

@jeffersonrabb let me know if you're not seeing the same problem with 7.9+!

**Comment by laurelfulford** [comment]
This issue has a PR in the theme repo, which seemed to make more sense after digging into exactly what was still working, and what was not :)
