### ISSUE TITLE
Editor view rearranges columns to match mobile ordering

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-blocks#434]
The editor view of the homepage will unexpectedly shift columns around to match the priority given to the columns for mobile display. For instance, in a 25-50-25 three-column layout, the emphasis is on the center column. So it's reordered for mobile for the center column to be shown first. Until recently, that reordering didn't affect the view in the editor. 

Frontend of Ye Olde Newspack.blog:
![Screen Shot 2020-04-22 at 2 03 41 PM](https://user-images.githubusercontent.com/48489469/80022769-29424a00-84a2-11ea-9a96-131c7cf27c7c.png)

Backend editor view:
![Screen Shot 2020-04-22 at 2 04 06 PM](https://user-images.githubusercontent.com/48489469/80022854-4545eb80-84a2-11ea-9342-7f95d4c22b84.png)

I saw the issue happen when I was giving a demo. I added Style 2 from the Newspack Patterns. It wasn't immediate, but somewhere along the line, the editor view shifted. Sorry that I can't immediately reproduce. I'll keep trying to see what triggers it.

**Comment by laurelfulford** [comment]
I can recreate this -- seems to be related to some CSS class changes in Gutenberg 7.9+ (in 7.8.1 and lower, it previews as expected).

**Comment by laurelfulford** [comment]
... and now I can't. I can see it on the newspack.blog site though -- going to keep on digging!
