### ISSUE TITLE
Article Carousel: Can Tab through slides without using the interactive buttons

### ISSUE THREAD

**Issue by jeryj** [Automattic/newspack-blocks#436]
**Describe the bug**
When you're navigating the slides via keyboard, you can tab through the slides without using the buttons. 

Based on the `<amp-carousel>` examples, I _think_ it's possible to have this interaction work: https://amp.dev/documentation/examples/multimedia-animations/image_galleries_with_amp-carousel/?format=websites. Some of them work to bring you to the buttons instead of tabbing through the images, a some work like the screenshot I uploaded.

**To Reproduce**
1. Create an Article Carousel
2. View it on the Front-end site
3. Tab to the Article Carousel
4. Keep on Tabbing :)
5. See the slides change before you reach the buttons.

**Screenshots**
![article-carousel-tabbing](https://user-images.githubusercontent.com/967608/80148419-a3de9880-857a-11ea-8769-610240f40397.gif)

**Expected behavior**
When tabbing through a carousel, it should go from the content in the current slide and then move to the "next" carousel control button.

**Comment by jeffersonrabb** [comment]
When the Jetpack Slideshow block was in testing, we did an accessibility review here: `p1HpG7-6jw-p2`. If I'm understanding correctly, the item titled `Using it with a screen reader, I can’t actually move into the individual slides.` is addressing the same question as this issue, but describes the opposite behavior as expected.

**Comment by jeryj** [comment]
Thanks for looking into this, @jeffersonrabb! 🙌 It's awesome that an a11y review was done for this block. Major kudos there!

> Using it with a screen reader, I can’t actually move into the individual slides.

You should definitely still be able to tab into a slide, but only the current slide should be in the focus order. The rest should not be able to receive focus until they're the current slide.

Here's the current focus order:
- slide one post title
- slide one post author
- slide two post title
- slide two post author
- etc for the rest of the slides
- Previous button
- Next button
- Navigation buttons

I could see arguments for a couple different ways and I'm torn on what the best focus order would be. I _think_ this is the one I'd recommend though if I had to choose.

- Previous Button
- Current Slide Title
- Current Slide author
- Next Button
- Navigation buttons

I like that once you're on a slide, to continue to the next slide you don't have to tab through the previous button as well. However, when you first enter the slider, you'd see the Previous button on content you haven't even encountered. But, focusing the Previous button first would follow the visual focus order, which is a point in its favor.

As far as actual implementation, let me know if you want any ideas! I think there are a couple ways that could work, but I'm not sure what would be the most accessible outcome without diving in a bit deeper.

**Comment by jeryj** [comment]
I can help out with this tomorrow 👍
