### ISSUE TITLE
Homepage Blocks: Add option to show categories

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#44]
Right now, articles in the homepage blocks just show title, excerpt, author info, publish date and featured image.

They did originally show categories, but in application, it turned into a lot of visual noise -- in a category-specific section, you end up with the same word over and over.

However it could be handy for blocks that query latest, top, editor's picks -- any blocks of articles that include a variety of topics. 

Potential issues:
* Show one category or all? The latter could be a long list, and look clunky; the former could be tricky, since it would either pick the 'first' category (which I believe is either the first assigned, or the one with the lowest ID), or we'd need a mechanism to select a specific category to show on a per article basis.

**Comment by claudiulodro** [comment]
This feature was added a while ago
