### ISSUE TITLE
Articles Carousel: missing placeholder for empty state

### ISSUE THREAD

**Issue by frontdevde** [Automattic/newspack-blocks#443]
**Describe the bug**
When there are no posts with featured images, the Articles Carousel renders without slides. To the user this will appear broken and leaves them at a loss as to what is wrong.

**Expected behavior**
We should provide the user with clear instructions on how to resolve the issue. Ideally, when there are no featured image posts, there should be a placeholder instead of the carousel that tells the user that they need to add featured images to their posts in order for those to appear in the Articles carousel. 

**To Reproduce**
1. Create posts without a featured image
2. Create a new post and added the Articles Carousel

**Screenshots**

<img width="1345" alt="Screenshot 2020-04-28 at 13 38 11" src="https://user-images.githubusercontent.com/1562646/80483355-3ce42980-8956-11ea-8e9f-7a6b83718e9d.png">

**Comment by marekhrabe** [comment]
<img width="591" alt="Screenshot 2020-05-01 at 16 41 04" src="https://user-images.githubusercontent.com/156676/80813857-2561a680-8bcb-11ea-9b82-ca481bee98e9.png">

I have just tested our FSE feature branch https://github.com/Automattic/wp-calypso/pull/41423 and I'm getting this result.

**Comment by jeffersonrabb** [comment]
The primary problem was addressed by the changes in https://github.com/Automattic/newspack-blocks/pull/440, although we may also want to address the appearance of the message. I'm guessing the text was originally centered and Gutenberg changes broke the alignment. @thomasguillot is this correct, and should we rework this state?

**Comment by jeffersonrabb** [comment]
Related: https://github.com/Automattic/newspack-blocks/issues/430

**Comment by marekhrabe** [comment]
I haven't checked the code but if it is using `<Placeholder>`, then indeed it changed its alignment from center to left recently in Gutenberg.

**Comment by thomasguillot** [comment]
> I'm guessing the text was originally centered and Gutenberg changes broke the alignment. @thomasguillot is this correct, and should we rework this state?

Correct. We could simply remove the prev/nav buttons since there aren't any posts.

**Comment by marekhrabe** [comment]
Would it be worth saying "no posts with featured image" in the placeholder message? Because you can have posts present but they will be ignored unless they have an image

**Comment by marekhrabe** [comment]
Changing the message to mention featured images would go long way in terms of being clear why posts don't show up even if you have some published…

**Comment by iamtakashi** [comment]
+100 for a better empty state. At the moment, it's confusing why there are no posts were found when the site has published posts.

Why don't we show posts regardless of the existence of the featured images and provide a placeholder image or something like that?
