### ISSUE TITLE
Carousel Block: Use Swiper For Non-AMP Requests

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-blocks#449]
#### Background

The Carousel block began as an experiment to use an AMP component ([`amp-carousel`](https://amp.dev/documentation/examples/components/amp-carousel/)) in both AMP and non-AMP requests. The AMP team is working on a project called [Bento AMP](https://blog.amp.dev/2019/05/01/amp-as-your-web-framework/) to make AMP components usable on non-AMP pages. This initiative is still in development, but the Carousel block was essentially an experiment to see if this approach could be taken by simply including AMP scripts in a non-AMP page. And... It worked!

#### The Risk

The problem is that there may be difficult-to-predict side effects from including AMP scripts in non-AMP pages. These might include image sizing irregularities, form submission problems, script conflicts, etc. None of these have been observed thus far, but with the move to bring Carousel to WP.com the block's footprint will be much larger, and the possibility of nasty surprises much higher.

#### Proposed Solution

The [Jetpack Slideshow block ](https://github.com/Automattic/jetpack/tree/master/extensions/blocks/slideshow) uses [Swiper](https://swiperjs.com/) to power the carousel in non-AMP requests and `amp-carousel` in AMP pages. The functionality is acceptably similar between the two. In Carousel we should take the same approach. Swiper is already being used to power the block in the editor, so the integration and styling is already more or less there. This will remove the risk of including AMP libraries in non-AMP pages, and should be a much safer way to go.

**Comment by obenland** [comment]
> script conflicts, etc. None of these have been observed thus far
I saw one yesterday when it seemed that Google had shipped a faulty version of their script.
Unfortunately I couldn’t reproduce it reliably, so I didn’t report it. 

Making that part a bit more robust sounds like a good idea. It would also help with sliders staying intact in case those AMP scripts change unexpectedly.
