### ISSUE TITLE
Carousel Doesn't Work In IE11

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-blocks#464]
**Describe the bug**
In IE11, the carousel buttons do nothing. In AMP requests the Carousel does work but in non-AMP it fails.

**To Reproduce**
1. Create a post, add Posts Carousel block.
2. Test in IE11 (non-AMP), buttons do not function.

**Comment by claudiulodro** [comment]
WP doesn't support IE11 any more
