### ISSUE TITLE
Byline Invisible In Posts Carousel Block

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-blocks#465]
**Describe the bug**
In Posts Carousel block, author name is not visible in front end. In the editor it is visible, but styling conceals it in published post. 

**To Reproduce**
1. Add Posts Carousel block to a Post.
2. Make sure "Show Author" and "Show Author Avatar" are toggled on.
3. Publish the post and view. 
4. Observe that the byline is hidden.

**Screenshots**
Editor:
<img width="1555" alt="Screen Shot 2020-05-06 at 4 41 52 PM" src="https://user-images.githubusercontent.com/1477002/81226239-87018680-8fb8-11ea-9e5f-9790f363b6b3.png">

Frontend (non-AMP):
<img width="1555" alt="Screen Shot 2020-05-06 at 4 42 43 PM" src="https://user-images.githubusercontent.com/1477002/81226305-a4365500-8fb8-11ea-8676-ebc8c36d49e3.png">

Frontend (AMP):
<img width="1555" alt="Screen Shot 2020-05-06 at 4 43 09 PM" src="https://user-images.githubusercontent.com/1477002/81226343-b2847100-8fb8-11ea-9522-bcd71141132f.png">

CSS that is causing the problem:
<img width="362" alt="Screen Shot 2020-05-06 at 4 44 46 PM" src="https://user-images.githubusercontent.com/1477002/81226630-2757ab00-8fb9-11ea-8983-19a7102f0b7a.png">

**Expected behavior**
Byline should be visible in front-end just as it is in the editor.

**Comment by obenland** [comment]
Where does this style originate?
