### ISSUE TITLE
Articles Carousel: Height jump when going to previous slide

### ISSUE THREAD

**Issue by jeryj** [Automattic/newspack-blocks#470]
When using images of different heights, if you cycle forwards a few times, then cycle backwards, the height of the slider will jump to the size of the smaller height.

![article-carousel-height-jump](https://user-images.githubusercontent.com/967608/81413294-cc35cd80-910a-11ea-9133-42f6cbc4b74b.gif)

**To Reproduce**

1. Create a slider using two images with significantly different ratios/heights. I used the two attached images below.
2. Cycle forwards through the slider a few times, then go backwards.
3. See the height jump to match the smaller image. Now all slides will be the smaller height.

**Images for reproducing**
![IMG_2327](https://user-images.githubusercontent.com/967608/81413045-65181900-910a-11ea-9d57-b193534adfea.jpeg)

![IMG_4189 (2)](https://user-images.githubusercontent.com/967608/81413049-68130980-910a-11ea-8f78-5c91351a64b9.jpeg)

**Expected behavior**
The height of the slider should be consistent across all slides, or jump to match the height of the new slide each time.

**Comment by jeffersonrabb** [comment]
I haven't been able to reproduce this one, even using the exact images in the example. Any other tips on how to make it happen?

**Comment by jeryj** [comment]
The things I noticed to reproduce it were:
- Chrome
- Have devtools open
- Have a wide (1100px or wider screen)

When you load the page, if the slider is taller than normal, the bug is present. It seems like it miscalculates the initial height, then, for some reason, figures it out after cycling to previous slides.

**Comment by adekbadek** [comment]
Could not reproduce with the above instruction. Could you check again, @jeryj ?

**Comment by jeryj** [comment]
@adekbadek, I don't have a quick way to set up the dev environment and test case for this (nor do I remember it enough 😅). I'd say if you tried and couldn't repro and no one else has reported this in a year, that it's safe to close for now.
