### ISSUE TITLE
Blog Posts Block: any additional block can only show posts that are not already shown in the previously added Blog Posts Blocks on the same page

### ISSUE THREAD

**Issue by zdenys** [Automattic/newspack-blocks#481]
**Describe the bug**
It seems like a bug but maybe it's a feature. When you add more than one instance of the block to the page, any additional block can only show posts that are not already shown in the previously added Blog Posts Blocks on the same page.

**To Reproduce**
1. Add Blog Posts Block (which will show all posts by default)
2. Add one more Blog Posts Block
3. See message `Sorry, no posts were found.` for the second block
4. Set a rule in the first Blog Posts Block (for example only show one category)
5. See the second Blog Posts Block populated with all the posts that are not already shown in the first Blog Posts Block.

**Screenscast**
https://d.pr/v/eOdA3K

**Expected behavior**
Be able to show all posts in any additional Blog Posts Blocks added to the same page. If it is a feature, then we need to make it clear in the support document. Hence I created https://github.com/Automattic/en.support-docs-content/issues/629

#user-report 2978097-zen

**Comment by laurelfulford** [comment]
Hey @zdenys!

This is indeed working as designed -- it's meant not to show a post more than once on a page, so you don't end up with the same post appearing in multiple blocks.

That being said, this isn't the first time we've been asked about being able to turn that off :) I'm going to move your report to #258, as it covers a request to add a toggle to turn off the deduplication.
