### ISSUE TITLE
Latest Posts Block not displaying correctly

### ISSUE THREAD

**Issue by fresatomica** [Automattic/newspack-blocks#482]
## Steps to replicate

Add the Latest Posts Block to a page and choose to display posts with featured images.

## Result

The last item has a different height.
![Screen Shot 2020-05-18 at 11 57 41](https://user-images.githubusercontent.com/40177971/82200643-8db8c380-98ff-11ea-9153-45923174753b.png)

## Expected

Items should have same height.

* User report: https://wordpress.com/forums/topic/hever-theme-incompatible-with-blog-posts-grid-view-show-media-behind/

A user reported that the bug is caused by this piece of CSS:
`@media only screen and (min-width: 782px)
.wpnbha.is-grid article, .wpnbha.is-grid article:last-child {
margin-bottom: 1em;
}`

**Comment by nielslange** [comment]
@fresatomica Thanks for reporting this issue. As this issue is caused by the Newspack Blocks, I transferred it from https://github.com/Automattic/themes/issues/ to https://github.com/Automattic/newspack-blocks/issues/. The link you shared in the forums already redirects to this issue, though.

**Comment by laurelfulford** [comment]
We've had another report of this in a comment in #396 -- user report: #21637853-hc

It looks like they've since switched themes.
