### ISSUE TITLE
Post Carousel Block (WP.com): Allow for alignment options

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/newspack-blocks#502]
**Is your feature request related to a problem? Please describe.**
We should allow users to set the block to different alignment types: Wide, Full Width, to make the block options better and more in line with other blocks we have in the platform.

**Describe the solution you'd like**
Allow for alignment options selection on the block top toolbar.

**Comment by laurelfulford** [comment]
Thanks for reporting this, @davipontesblog!

It looks like a duplicate of #488, so I'm going to close this specific issue; if if you think anything is missing from that issue, please add a comment. Thanks!
