### ISSUE TITLE
Carousel: image gets cropped on Publication theme

### ISSUE THREAD

**Issue by bsanevans** [Automattic/newspack-blocks#504]
**Describe the bug**
In the Publication theme, the images in the carousel get cut off in both Previewed and Published posts. The block works fine in the editor.

![carousel-on-publication](https://user-images.githubusercontent.com/49054298/83494006-978e1980-a4f0-11ea-82cd-0ba01b256eb8.png)

For comparison, this is what the same post looks like on Twenty Twenty.

![carousel-on-twentytwenty](https://user-images.githubusercontent.com/49054298/83494147-cad0a880-a4f0-11ea-8dbd-11dbb0e21360.png)
 

**To Reproduce**
1. Add a Carousel to any post or page
2. Set the site theme to Publication

**Workaround**
Adjusting CSS on .post-thumbnail fixes the issue. Does this suggest conflicting CSS classes?

![carousel-on-publication-with-css](https://user-images.githubusercontent.com/49054298/83494373-2438d780-a4f1-11ea-8aed-e1cd617d54e7.png)

**Support**
The user is on the free plan, so adding CSS is not an option. Should the theme be tweaked to allow for the block, or the other way around?

Ticket: 3011370-zen

**Comment by edwinho89** [comment]
Another user had reported the same issue, where user is using Dicot theme experiencing similar issue.

Provided CSS as workaround as below:

```
.wp-block-newspack-blocks-carousel figure.post-thumbnail {
    width: 100%;
}
```

ZD: 3099253-zen

**Comment by rinazrina** [comment]
Another report: 3896064-zd-woothemes

Theme: Publication
