### ISSUE TITLE
Blog Posts Block: Show More Missing on Unlaunched Site

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/newspack-blocks#507]
#### Steps to reproduce

1. Starting at URL: wordpress.com/start
2. Create a new unlaunched site
3. Since the new site usually has three test posts, on a new page, add the Blog Posts block
4. Note under Settings for the block, the option to toggle the Show "More" Button does not appear
5. Without making any changes to content, launch the site from Settings
6. Return to the page with the Blog posts block and note that the Show "More" Button is now available

#### Screenshot / Video

No Show "More" Button toggle on unlaunched site
![Screen Shot 2020-05-20 at 14 53 20](https://user-images.githubusercontent.com/38542929/82485753-e88e1e80-9aa9-11ea-94e9-03226bafa3a8.png)

Show "More" Button toggle on launched site
![Screen Shot on 2020-05-20 at 14-53-30](https://user-images.githubusercontent.com/38542929/82485710-d90ed580-9aa9-11ea-87f8-51d3eaf0e57b.png)

#### Context / Source

21242212-hc
#user-report

**Comment by tullyhansen** [comment]
Possibly related but not an exact match, multiple Blog Posts blocks on one page not showing more than one Load More Posts button (first block on page):

- [21606477-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=21606477) | [3029980-zd](https://woothemes.zendesk.com/agent/tickets/3029980)
- [SA](https://wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=ericarobbin)
- Example page: https://wordpress.com/block-editor/page/ericarobbin.com/5627 | https://ericarobbin.com/thoughts-for-a-rainy-day/
- [#wpcom-support Slack thread](https://a8c.slack.com/archives/C03TY6J1A/p1591248218086600)

**Comment by tullyhansen** [comment]
Same behaviour (Show More Missing on Unlaunched Site) also noted at https://github.com/Automattic/newspack-blocks/issues/397#issuecomment-596740714

**Comment by tullyhansen** [comment]
Could this issue please be renamed something like _Blog Posts Block: 'Show "More" Button' toggle missing on unlaunched site_? As I've been digging into this there's some slippage between terminology (_Show "More" Button toggle_ vs _Load More Posts button_) and it would be great to clarify, as it seems there are separate (related) issues.

**Comment by adekbadek** [comment]
This is because the unlaunched site is not public, and the "Load more" button on WPCOM sites fetches the posts via public API (#306):

https://github.com/Automattic/newspack-blocks/blob/31181a5536aef03779cf789d2dcd4d9de05b4371/src/blocks/homepage-articles/edit.js#L307-L313

I think a solution might be to add add a note about it in place of the hidden setting.

**Comment by Robertght** [comment]
I found another case in #3279951-zen which took me a while to find the answer to.

**Comment by chad1008** [comment]
Another report in 23871451-hc on a "Coming Soon" site.
