### ISSUE TITLE
Strange text transformation in Ad Unit names

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-blocks#51]
From @sonjaleix in #39:

> To replicate, create an ad unit and call it "Ad 300x250". Once you've saved the ad unit and you land back on the ad units overview screen you'll see the ad unit name display as "Ad 300×250". See screenshot:

Needs more investigation and fuller big report...

**Comment by jeffersonrabb** [comment]
Fix for this is in https://github.com/Automattic/newspack-plugin/pull/176
