### ISSUE TITLE
Blog Posts Block: Load More Posts button only shows on first of multiple block instances

### ISSUE THREAD

**Issue by tullyhansen** [Automattic/newspack-blocks#510]
Multiple **Blog Posts** blocks on a single page seem to never show more than one **Load More Posts** button on Preview & published pages. Reproduced at https://widgettheworldwatcherfansite.blog/blog-posts-block-test/ as follows:

- Three **Blog Posts** blocks, all set to 3 items/3 columns/**Show More** enabled
- Each **Blog Posts** block set to show posts from different exclusive categories, 6/3/6 posts respectively

**Findings**

- Each block with **Show More** enabled shows a **Load More Posts** button while editing, but this is not necessarily reflected in Preview or published post
- Regardless of whether first block on page shows a **Load More Posts** button or not, no block further down will show a **Load More Posts** button
- Regardless of whether first block on page has **Show More** enabled or not, no block further down will show a **Load More Posts** button

Allowing multiple instances of **Blog Posts** block on page seems to be a relatively recent development (March 2020, p5cPuC-29b-p2#comment-2468).

_21606477-hc • 3029980-zd • p1591268313195200-slack-wpcom-support_

_Originally posted by @tullyhansen in https://github.com/Automattic/newspack-blocks/issues/507#issuecomment-638779333 – on reflection seemed to warrant a separate issue_

**Comment by cecilearkay** [comment]
Also reported in 21535844-hc

![Screen Shot 2020-06-05 at 10 30 09](https://user-images.githubusercontent.com/16645645/83855523-7c9dee00-a718-11ea-8164-0c261b4d6dc5.png)
