### ISSUE TITLE
Blog Posts Block: sharing buttons don't show on simple sites

### ISSUE THREAD

**Issue by brookewp** [Automattic/newspack-blocks#511]
**Describe the bug**
Likes/sharing buttons don't show beneath posts for the Blog Posts block on simple sites, only on Atomic sites. 

**To Reproduce**
1. Add a Blog Posts block to a new page or post 
2. Publish changes 
3. See that sharing/like button don't show (even with pages enabled from marketing > sharing buttons)

**Expected behavior**
That the likes and sharing buttons would show beneath each post if sharing buttons/likes are enabled for the page/site. 

Simple with bug: 
<img width="270" alt="Screen Shot 2020-06-05 at 11 07 18 AM" src="https://user-images.githubusercontent.com/35543432/83909130-136ca980-a71d-11ea-8d08-d8137a54d9ab.png">

As expected: 
<img width="283" alt="Screen Shot 2020-06-05 at 11 07 39 AM" src="https://user-images.githubusercontent.com/35543432/83909143-19628a80-a71d-11ea-81a0-bccbdecf802f.png">

**Comment by adekbadek** [comment]
Closing for now. The code is this repository does not handle adding this UI, it's appended by some other code.
