### ISSUE TITLE
For NRH Checkout Customers Donate Block Suppressed If WooCommerce Inactive

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-blocks#518]
**Is your feature request related to a problem? Please describe.**
Newspack customers using the NRH checkout option do not need to run WooCommerce or any of the Woo extensions associated with the reader revenue wizard. However, if WooCommerce is not running, the Donate block will be hidden. 

**Describe the solution you'd like**
Change the block's display logic to account for activation status of the NRH Checkout plugin.

**Additional context**
Originally came up for @sonjaleix related to Oaklandside.

**Comment by adekbadek** [comment]
Closed in https://github.com/Automattic/newspack-plugin/pull/726
