### ISSUE TITLE
Blog Posts Block: post links with multiple hyphens in post content 404

### ISSUE THREAD

**Issue by brookewp** [Automattic/newspack-blocks#520]
**Describe the bug**
When a link has three hyphens in it, they are converted into an en/em dash in the Blog Posts block, which causes a 404 when going to the link. 

**To Reproduce**
1. Add a link that contains three dashes to a post - [link example here](https://www.rcgp.org.uk/clinical-and-research/about/clinical-news/2020/february/uk-physical-activity-and-lifestyle-guidelines---what-is-new.aspx)
2. Add a Blog Posts block to a page
3. Click on the link on the page with Blog Posts block
4. See 404 page

**Screenshots**

<img width="816" alt="Screen Shot 2020-06-11 at 5 49 30 PM" src="https://user-images.githubusercontent.com/35543432/84453037-54c4f380-ac0c-11ea-8445-3c3c09302f69.png">

**Expected behavior**

That the link behavior would be the same in the Blog Posts block as it is within the single post where it works.

**Comment by laurelfulford** [comment]
Hey @brookewp! I'm running into a similar issue recreating this as I did with #521 -- I've tried adding the link to the custom excerpt, but when I click on it, it looks like it's preserving the double-hyphen in the URL, and it's pulling up the page for me. 

If you have an example to link to where this is happening, it'd be a huge help! I feel like I'm missing a step or specific setting, and that should help shake it out -- thanks!

**Comment by laurelfulford** [comment]
I've added a better explanation for this in #521, but these issues don't appear to be related to the Newspack Blocks specifically, but something weird that you can get `the_excerpt` to do on WP.com.

I'm going to close this issue since it's not specific to the Newspack Blocks, but if you have any questions at all please let me know!
