### ISSUE TITLE
Blog Posts Block: Add option for CPT (custom post types)

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/newspack-blocks#522]
Currently we need to use the Portfolio Shortcode to display Portfolio projects on a post or page. The shortcode is pretty clunky, especially when compared to the Blog Posts Block.

_What about adapting the Blog Posts Block to display Portfolio projects instead?_ 

So just as the Blog Posts Block enables users to display their posts based on various parameters using a set of layout options, how about creating a version of that block for Portfolio projects too?

Options in the Blog Posts Block could be perfect for this use case. For example, [like this](https://d.pr/i/6LmM1S/hNZ3YpUKVQ):

![](https://d.pr/i/6LmM1S/hNZ3YpUKVQ+)

_Screenshot direct link:_ https://d.pr/i/6LmM1S/hNZ3YpUKVQ

This may be related to Automattic/wp-calypso#37782

**Comment by benmay** [comment]
Same issue. Would be happy to do this via a filter, if that is acceptable happy to do a PR.

**Comment by laurelfulford** [comment]
We've been discussing this option from a Newspack perspective; Newpack already includes a custom post type for Newsletters, and additional ones like Listings and Podcasts are potentially in the works. Those, on top of pages, would be very handy to be able to show on the front-end.

On the flip side, we also have a bunch of CPTs, like for sponsors and campaigns, that we wouldn't want to show, or even have available to pick. I'm sure there are other CPTs out there that wouldn't be appropriate to show in this block.

**Based on this:**
* A filter-based approach makes sense -- support could be added for CPTs to the blocks, and individual plugins could opt-in using the filter.
* By default, the block could have both posts and pages available.
* For our purposes on Newspack, it would be ideal to intermingle post types -- like show posts and newsletters together. But that could introduce some complexities (see below).

**Some considerations:**
* Some CPTs use custom taxonomies (like Portfolios in Jetpack). Should these be options, too? How would they work for if multiple post types can also be selected?
* With the inclusion of pages (and something like listings!), it might make sense to offer additional ordering options, like alphabetical, as long as that doesn't cause issues with the other settings.
