### ISSUE TITLE
Multiple ad units don't or inconsistently render within the same post on front-end

### ISSUE THREAD

**Issue by sonjaleix** [Automattic/newspack-blocks#53]
**Describe the bug**
When checking out #39 and testing the block, I'm getting a weird bug. When I'm adding multiple (3) Ad Manager blocks in one post and viewing the post on the front-end I see two of three ads render in the post at once, sometimes just one, sometimes all three. And upon each page load it’s different ad units that load. 

Looking to see if anyone else is getting the same bug. Since I'm using AMP ad code, I wonder if the AMP errors in my local install might contribute to this issue, so I'll share that below as well.

Related to #39 

**To Reproduce**
1. Upon checking out PR #39, go to Newspack > Advertising > Google Ad Manager wizard
2. Set up three ad units: 
2.1 Title: "Ad unit 300 x 250"
`<amp-ad width=300 height=250
    type="doubleclick"
    data-slot="/21819266620/ll_sidebar_med_rect">
</amp-ad>`
2.2 Title: "Ad unit multi-size"
`<amp-ad width=468 height=60
    type="doubleclick"
    data-slot="/21819266620/sdfsdf"
    data-multi-size="320x50">
</amp-ad>`
2.3 Title: "Ad banner 728 x 90"
`<amp-ad width=728 height=90
    type="doubleclick"
    data-slot="/21819266620/fsadfsdf">
</amp-ad>`
3. Then create a new post in the Gutenberg editor
4. Place all 3 ad units in the same post with the "Google Ad Manager" block by selecting the individual ad unit in the block settings in the right sidebar under the Advert dropdown
5. Publish the post and view on front end
6. Now reload the post a few time
7. I see different ads load with each reload, sometimes just one, sometimes two, sometimes all three

**Gif of what I'm experiencing on reloads**
https://drive.google.com/file/d/1oKKaHBcmxVmG3TT5ezWznQGkEC1ETcQF/view?usp=sharing

**AMP errors that might contribute**
Most of the AMP errors have something to do with Woo or other plugins, but the last one I've expanded seems to be specific to the Ad Manager block: https://www.dropbox.com/s/ohfz0k8xvbjihg3/amp-errors.png?dl=0

**Expected behavior**
All ad units on a page should render and not conflict with each other or other factors. This also includes any fixed ad spots in header, footer, or sidebar we're planning for.

**Comment by jeffersonrabb** [comment]
Instances of the block that are onscreen when the page loads will render while any that are offscreen (below or above the scroll) will not. According to the  [AMP docs](https://amp.dev/documentation/components/amp-ad#no-ad-available), Ad Units that fail to fill will be hidden unless the Ad is in the viewport. This is done to avoid jarring changes to the content. If this theory proves correct, the problem we're having is solely because we're not testing with real units. Let's get some  real units to test with and see if this proves true...

**Comment by jeffersonrabb** [comment]
This refers to a block that was relocated to https://github.com/Automattic/newspack-ads.
