### ISSUE TITLE
Homepage Posts: "Load More" button removes classes 😬 

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#534]
When using AMP mode, clicking the "Load More" button strips out the CSS classes on the main containing `div` and replaces them with `[object Set]`. Most of the block styles are tied to these classes, so it causes a lot of visual breakage. 

This doesn't happen when AMP is not enabled.

**Comment by jeffersonrabb** [comment]
A quick fix is to remove all six lines where `classList` operations occur in https://github.com/Automattic/newspack-blocks/blob/master/amp/homepage-articles/view.js, which will remove the UI state change during loading. Looking into any changes in `amp-script` which may have caused this, but if we aren't able to find the answer quickly we can simply remove the `classList` manipulation.

**Comment by jeffersonrabb** [comment]
This turned out to be an `amp-script` regression. Filed [here](https://github.com/ampproject/amphtml/issues/29037), resolved [here](https://github.com/ampproject/worker-dom/pull/879). The problem should be resolved with no change needed to the Homepage Posts block.
