### ISSUE TITLE
Posts Carousel block - "No Posts Found" if there's no featured image

### ISSUE THREAD

**Issue by sdixon194** [Automattic/newspack-blocks#542]
The Posts carousel block currently just displays "Sorry, no posts found." if none of the site's published posts have featured images. This can be misleading when someone hasn't set up posts with featured images since they're expecting the block to still  show something.

**Describe the solution you'd like**

Have the posts appear with a solid color in place of a featured image so at least something is there.

**Alternatives**

Display a clearer message indicating that they may have to add featured images to posts. 

**Additional context**

![Screen Shot on 2020-07-02 at 10:42:46](https://user-images.githubusercontent.com/33553323/86386013-2bbdde80-bc5f-11ea-906b-493215e8e184.png)

**Comment by nickpagz** [comment]
A similar issue today with another user in #24575859-hc
The difference was the messaging, this time:

> This block has encountered an error and cannot be previewed

Adding a featured image to a post solved the issue. Thanks to @samiff for the catch! Agreed with @sdixon194 - we need better messaging on this one.

**Comment by ramonjd** [comment]
I just ran across this today again. For me, it's frustrating to have to guess that posts require a feature images before they appear in the carousel.

Nowhere are the requirements clearly stated.

What if we update the placeholder and block description in the editor? Examples:

<img width="651" alt="Screen Shot 2021-07-14 at 8 38 22 pm" src="https://user-images.githubusercontent.com/6458278/125609071-779e4c24-fe93-4237-8f27-f85b1fa6ee98.png">

<img width="295" alt="Screen Shot 2021-07-14 at 8 39 26 pm" src="https://user-images.githubusercontent.com/6458278/125609080-7289e476-fa1b-4489-a8d7-7372ab1ff9e1.png">

**Comment by andrewserong** [comment]
That wording looks good to me, @ramonjd!

**Comment by laurelfulford** [comment]
It looks like the original issue  -- posts without featured images are not displayed -- was resolved with a slightly different approach in #731 (rather than updating the message, the block was updated to always show the posts, regardless if they have an image). 

I'm going to close this issue as it's technically fixed but if there are any questions please let me know!
