### ISSUE TITLE
Donate Block: Add option to customize "Your contribution is appreciated" text

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#545]
Like the button text, it would be awesome to make it possible to customize the "Your contribution is appreciated" text in the block, whether it's to make the message match the other verbiage the publication is using around donations, or to remove the text to hide that bit all together.

**Comment by joeboydston** [comment]
This is a launch blocker for The Beacon. They want to customize the "Your contribution is appreciated" text by adding multiple lines as seen in this mockup.

<img width="777" alt="Screen Shot 2020-09-01 at 11 27 13 PM" src="https://user-images.githubusercontent.com/22623115/91935390-d330af00-ecaa-11ea-8736-72c42abe465e.png">

**Comment by laurelfulford** [comment]
@joeboydston in that example, is the text meant to be the same for each of the donation amounts, or change (so if you're donating $10, it's different than when you're donating $20)? If the latter, that might be better handled on a page explaining the perks of donating -- otherwise, the complexity could be beyond what we'd want to adding to this block.

**Comment by jonnyruzek** [comment]
User in 29152656-hc would also like an option to be able to customize their "thank you" text.

**Comment by tmmbecker** [comment]
ML requested this as an option too.
