### ISSUE TITLE
Blog Post Block: LinkedIn Sharing icon is not aligned with others

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/newspack-blocks#554]
**Describe the bug**
When using the Blog Post block with Sharing Buttons enabled, if the Official Button style is selected, the LinkedIn button is out of alignment with the others.

**To Reproduce**
1. Create new page with Blog Post Block
2. Set Sharing Buttons style to "Official Buttons"
3. Add Twitter, Facebook, and LinkedIn sharing buttons
3. View Blog Post Block page

**Screenshots**
![screenshot](https://d.pr/i/XRN3Gg+)
Image URL: https://d.pr/i/XRN3Gg

**What happened**
LinkedIn sharing button was not aligned with the others

**Expected behavior**
Expected to see sharing buttons aligned correctly

**Temporary CSS fix**

```
.wpnbha button {
	margin-top: 0;
}
```

#3170967-zen

**Comment by adekbadek** [comment]
Closing for now. The code is this repository does not handle adding this UI, it's appended by Jetpack.
