### ISSUE TITLE
CAP Guest Authors aren't filterable in homepage posts

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-blocks#601]
**Describe the bug**
When using the Author filter in the homepage posts block, guest authors created using Co-Authors Plus are not available for filtering on.

**To Reproduce**
1. On a Newspack site with CAP activate
2. Ensure there is at least one guest author with at least one post
3. Add/edit a homepage posts block somewhere
4. In the Author filter type the name of the guest author
5. Observe that the guest author does not appear in the results

**Expected behavior**
CAP Guest Authors should behave exactly like normal WP Users when using the homepage posts block.

**Comment by tmmbecker** [comment]
WCP is now trying to use the Homepage posts block to add a link to all the most recent posts by an author to the bottom of their custom author pages. Example:

![Screen Shot on 2021-06-15 at 15-12-57](https://user-images.githubusercontent.com/22805865/122110145-3465e100-cdec-11eb-8db0-c8d0bc0253a3.png)

Their authors also work with freelancers and will create the draft articles on their behalf, even though the staff author is not officially an author on the post. That means that when they use the Homepage posts block for staff author, the freelancer's posts get incorrectly pulled in. 

Having Guest Authors as a filter option in the Homepage Posts block would solve both problems as they can simply select the guest author for all author pages.
