### ISSUE TITLE
Re-word "Load more posts" text

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-blocks#602]
**Is your feature request related to a problem? Please describe.**
The use of "posts" in "Load more posts" makes sense on a blog, but not so much when it comes to news publisher who are more likely to refer to their content as articles, stories, features, or something else.

**Describe the solution you'd like**
Either "posts" should be removed so as to be deliberately ambiguous and suit more use cases, or an option to rename "posts" to something else added.

**Comment by laurelfulford** [comment]
Hey @philipjohn! It's not super obvious, but you can edit the Load More Posts text by clicking on the button, and typing -- it doesn't automatically switch to a clear editor state, so it's a bit weird, but your text will replace what's there:

![image](https://user-images.githubusercontent.com/177561/99001680-1f407100-24f0-11eb-90dc-d0d56aaedcf3.png)

I'm going to close this ticket but just let me know if you have any questions!
