### ISSUE TITLE
Visual glitches in Newspack/Blog Post blocks in Internet Explorer 11

### ISSUE THREAD

**Issue by inaikem** [Automattic/newspack-blocks#606]
Via 3427206-ZD, we are seeing visual glitches in their Newspack/Blog Post blocks in Internet Explorer 11:

1. Columns not fitting on a single line
2. background images distorted/stretched

To reproduce, load the "live-well" page in the ticket above in Internet Explorer.

For **1.** scroll to "Featured Articles". They should be appearing in a single row, not broken as below.

> ![](https://d.pr/i/0aM6xz+)
[Can't see the image? Click this direct link.](https://d.pr/i/0aM6xz)
&nbsp;

For **2.** scroll to "Good Eats". The image containers show stretched/distorted background images.

> ![](https://d.pr/i/q4LFXZ+)
[Can't see the image? Click this direct link.](https://d.pr/i/q4LFXZ)

**Comment by adekbadek** [comment]
To reproduce the column layout issue, add a Homepage Posts Block with three columns and "Borders" style. On IE11 the padding [set here](https://github.com/Automattic/newspack-blocks/blob/0a557dcdc2a92684a654f6ce090a89ec97fc5f73/src/blocks/homepage-articles/view.scss#L683) will be slightly too much and will cause the flexbox to wrap the line.

**Comment by laurelfulford** [comment]
Given that WordPress [stopped supporting IE11 as of version 5.8](https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/), and [WordPress.com has a note that there may be display issues with it](https://wordpress.com/support/browser-issues/#supported-browsers), I think it might make sense for us to follow suit and close this issue as wontfix. I'm open to feedback on that idea, though! :)

**Comment by adekbadek** [comment]
Agreed, let's support what the core WP supports.
