### ISSUE TITLE
Homepage Post Block Should Not Show Password-Protected Posts

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-blocks#608]
**Describe the bug**
Currently the Homepage Posts Block will display posts with visibility Password-Protected. These should not be shown on a site's homepage because they are not meant to be generally available.

**To Reproduce**
1. Create a page with a Homepage Posts block, using no Category or Tag filteirng.
2. Create a post, set the visibility to Password-Protected and Publish.
3. View the page, observe the post appears in the block.

**Expected behavior**
Password-protected posts should not appear in Homepage Posts block.

**Comment by supernovia** [comment]
Just noting I've spotted a few cases today where someone said their posts were missing, but they were just password protected. I'll keep adding notes if we run into this more often.
https://wordpress.com/forums/topic/sorry-no-posts-were-found/

**Comment by supernovia** [comment]
Here was the other case from today: https://wordpress.com/forums/topic/blog-643/

**Comment by mikeicode** [comment]
Ran into confusion around this today.

The Latest Post and Carousel blocks _do_ display the password protected posts, so it's confusing that this block doesn't. Perhaps the block should have this as an option. I will open an enhancement request.
