### ISSUE TITLE
Asides: Unexpected placement in certain configurations of homepage posts block

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-blocks#610]
**Is your feature request related to a problem? Please describe.**
When using asides it often doesn't make sense to have a featured image. However, when they display in the homepage posts block this can result in the flow being interrupted which looks unexpected.

**Describe the solution you'd like**
Asides without a featured image ought to be given some sort of special treatment so that the different to standard posts is explained visually or in some other way.

**Describe alternatives you've considered**
Removing asides from the homepage posts block might be one option, but as support for asides was added to the Newspack theme with the intention that they are included in the normal flow, removing them from the homepage posts block would make the feature largely redundant.

**Additional context**

These examples use the following settings for the homepage posts block:

* Show featured image but not caption
* Don't show subtitle or excerpt
* Type scale of about 3
* Show date
* Don't show category
* Don't show author avatar

![Screenshot from 2020-10-27 11-47-02](https://user-images.githubusercontent.com/136342/97297809-6ec54280-184a-11eb-9718-39d5b6448d16.png)
![Screenshot from 2020-10-22 12-06-59](https://user-images.githubusercontent.com/136342/97297848-7b499b00-184a-11eb-8916-4c11231d3b33.png)

**Comment by laurelfulford** [comment]
In #1139 we removed support for the Aside post format -- going forward, in the blocks they will act/display like Standard posts. Because of that, this change is no longer required.
