### ISSUE TITLE
Asides: Clickable featured image

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-blocks#611]
**Is your feature request related to a problem? Please describe.**
If a featured image is assigned to an aside post, when it displays in the homepage posts block, the image is clickable even though the text etc isn't. That's unexpected as the aside is meant to be an isolated update that isn't clickable.

**Describe the solution you'd like**
Asides with featured images should not have the featured image linked to the post.

**Describe alternatives you've considered**
We could leave the link in which would be inconsistent with the rest of the post. We could not show the featured image at all, which might well make sense for asides, especially if we treat them differently as mentioned in #610.

**Additional context**
This was noticed by a publisher beginning to use the asides format.

**Comment by laurelfulford** [comment]
In #1139 we removed support for the Aside post format -- going forward, in the blocks they will act/display like Standard posts. Because of that, this change is no longer required.
