### ISSUE TITLE
Patterns: Drag/Drop of the thumbnail doesn't insert the pattern

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-blocks#621]
**Describe the bug**
When you drag and drop the thumbnail of a pattern onto your editor, instead of inserting the actual pattern, you insert the image

**To Reproduce**

**Screencast**
![Kapture 2020-11-05 at 15 55 04](https://user-images.githubusercontent.com/177929/98264232-9a99a400-1f7f-11eb-831f-ef422a64b79e.gif)

**Expected behavior**
Drag and drop should work just like a click and insert the pattern

**Comment by adekbadek** [comment]
After #639 this is not relevant anymore, the patterns can now be dragged & dropped.
