### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-blocks#622]
**Is your feature request related to a problem? Please describe.**
We have a Morrocan publisher who has their site set to Français de Belgique but we don't have a translation for that so some items like bylines aren't translated.

**Describe the solution you'd like**
The plugin should provide a Français de Belgique translation. 

**Describe alternatives you've considered**
Not sure there's another way to be honest!

**Comment by laurelfulford** [comment]
Closed with #626.
