### ISSUE TITLE
Donate Block: Add connection to send donations to NewsMatch pages

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#632]
Right now, NewsMatch can help publishers accept donations -- they have pages that look like [this](https://www.newsmatch.org/organizations/mission-local), and use a service called [GiveGab](https://www.givegab.com/) behind the scenes. Each of the donation buttons has a URL with a query string for amount, and it has options like frequency once you add them.

It would be super-handy to have the Donate block be able to send donations to these NewsMatch pages, similar to how it works with News Revenue Hub.

**Comment by adekbadek** [comment]
No intent to implement right now, we're pushing towards on-site donations for better handling of on-site messaging and first-party data.
