### ISSUE TITLE
Reader: Images not displaying when post contains "blog posts" block

### ISSUE THREAD

**Issue by ezebecke** [Automattic/newspack-blocks#636]
#### Steps to reproduce

1. Create a post with images 
2. Add a "blog post" block inside the post
3. Publish and check the post on the Reader

#### What I expected

To see all the images on the preview and inside the post content from the Reader view.

Post without "blog posts" block displays the images correctly inside the Reader:

Preview showing up correctly
<img width="870" alt="preview-w" src="https://user-images.githubusercontent.com/24919469/100117861-e03ce480-2e3a-11eb-951a-218421fddf3e.png">

Inside post in Reader showing up correctly
<img width="1080" alt="inside-reader-w" src="https://user-images.githubusercontent.com/24919469/100117879-e4690200-2e3a-11eb-8185-68b986513fd6.png">

#### What happened instead

Preview not showing images
<img width="887" alt="readernw2" src="https://user-images.githubusercontent.com/24919469/100118068-167a6400-2e3b-11eb-8f4c-fab06bc70f40.png">

Inside post in Reader not showing images
<img width="1153" alt="reader-nw" src="https://user-images.githubusercontent.com/24919469/100118090-1c704500-2e3b-11eb-998b-61b7cd5495e9.png">

**Comment by jartes** [comment]
Sometimes, after the Blog Posts block is removed, some images are still not displayed. 

As a workaround, I've duplicated one of the images (in my particular case, the first one), saved the post, and then removed the duplicated image, saved the post, and images were displayed on the reader.

**Comment by nellofn** [comment]
A user tried the suggested workaround of duplicating images, saving the post, and removing the duplicate but they said it didn't work on all posts.

**Comment by AtrumGeost** [comment]
Asked about this to the Reader team since I'm not able to replicate the issue on a test site by coping the content of the user's blog post:

p5PDj3-4XT-p2

**Comment by adekbadek** [comment]
Closing, since this seems to rather be an issue with the Reader and how it's processing post content.
