### ISSUE TITLE
Homepage Posts: Inconsistency with Columns block when using the grid style

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-blocks#638]
**Describe the bug**
When using the Newspack theme, there's an inconsistency with the margins. You'll notice it if you compare it to the columns block.

<img width="1440" alt="Screenshot 2020-11-27 at 17 02 50" src="https://user-images.githubusercontent.com/177929/100474205-04692180-30d8-11eb-83da-b9131194e9c0.png">

The gap should be 32px which doesn't seem to be the case.

**Suggestion**
I suggest we ditch flexbox and use css grid instead. We can also fine tune this for mobile.

<img width="1269" alt="Screenshot 2020-11-27 at 17 39 39" src="https://user-images.githubusercontent.com/177929/100474284-38dcdd80-30d8-11eb-81d9-ac4debc4da44.png">

_Note: there will be no need for `.wpnbha.is-grid article` margin bottom` since we will have grid gap_

**Suggestion 2**
We could also introduce a setting that controls the gap.

Eg:
S: 8px
M: 16px
L: 32px (default)

**Comment by laurelfulford** [comment]
Fixed with https://github.com/Automattic/newspack-blocks/pull/1245.
