### ISSUE TITLE
Blog Posts Block: Shows only latest 12 posts

### ISSUE THREAD

**Issue by mriyazuddin** [Automattic/newspack-blocks#662]
**Describe the bug**
When you use the Blog Posts block on a page, set the number of posts to be displayed to a certain number and enable the Load More Button, when you view the page on the live site and keep clicking Load More Posts, it shows only the last 12 and only in multiples of the number of posts to be displayed at a time. So, for example, if you have 13 posts and set the block to display 4 posts at a time, the Load More Posts button will not appear after 12 posts are displayed. Even if you add another 3-4 posts, the Load More Posts button displays only up to 12 posts and none after that. This happens on both simple as well as AT sites. Also, if you have say 11 posts then Load More Posts button does not appear after displaying 8 posts. You'll need to publish one more post to be able to see another 4 posts on the live page or in preview.

**To Reproduce**

1. Ensure you have at least 13 or more posts.
2. Create a page, add Blog Posts bock and set it to display 4 posts at a time and display the Load More Posts button.
3. Preview the page or visit the live site.
4. Keep clicking Load More Posts button till you no longer see that button.

**Screenshots**
https://d.pr/i/OJx53e

**Expected behavior**
Load More Posts button should have appeared.

**Comment by sstabrizi** [comment]
I have another report of this in 26621396-hc, although the circumstances are a bit different. 

The user has 82 posts and has the block set to show 10 posts with the load more button enabled. I can press the load more button a maximum of 4 times, which means it's only possible to display a maximum of 50 posts. 

Is there something in the block that sets a maximum of clicking load more only 4 times? Is it possible to set that to an infinite number of times?

**Comment by supernovia** [comment]
This may also be related: https://github.com/Automattic/newspack-blocks/issues/404

**Comment by dkoo** [comment]
I believe this is the same as #404, which is resolved by #672 and will be in the next release to come shortly.

**Comment by laurelfulford** [comment]
It sounds like this should have been resolved with #672, so I'm going to close the issue, but if I have that wrong please do reopen or comment -- thank you!
