### ISSUE TITLE
Post Carousel: Use Custom Endpoint/Deduplication

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-blocks#664]
https://github.com/Automattic/newspack-blocks/pull/661 introduced a custom endpoint for Homepage Posts, and https://github.com/Automattic/newspack-blocks/pull/663 introduces support for custom post types. Post Carousel currently still uses the core REST API posts endpoint. 

If Post Carousel used the custom endpoint instead it would allow removal of all the [fields added to the REST API](https://github.com/Automattic/newspack-blocks/blob/master/class-newspack-blocks-api.php#L16-L134). 

This would also make it possible to support CPTs in Post Carousel.

Ideally, Post Carousel would also use the same deduplication logic as Homepage Posts, so the two could seamlessly coexists without post duplication.

**Comment by CodingSamurai** [comment]
> Ideally, Post Carousel would also use the same deduplication logic as Homepage Posts, so the two could seamlessly coexists without post duplication.

This is the BIGGEST gain by far in my opinion.  We have exactly this issue where if you mix a carousel on page with the homepage blocks you get duplicate content.
