### ISSUE TITLE
Conflict with NextGEN Gallery showing "The response is not a valid JSON response."

### ISSUE THREAD

**Issue by felipelousantos** [Automattic/newspack-blocks#665]
**Describe the bug**
Basically when we have the block "Blog Posts", it shows a generic "The response is not a valid JSON response." error as long as you have the [nextgen-gallery](https://wordpress.org/plugins/nextgen-gallery/) plugin is activated.

Reported in zen-3633315

**To Reproduce**
1. Install [NextGEN Gallery](https://wordpress.org/plugins/nextgen-gallery/)
2. Add the Blog Posts block on a page
3. If you still don't see the error, try saving/updating the page, and it should show "The response is not a valid JSON response."

**Screenshots**
https://d.pr/i/Thp1is

**Expected behavior**
It should work as expected without bringing the error "The response is not a valid JSON response."

**Comment by ccwalburn** [comment]
Another instance here: 4776277-zen
The error prevents the Load More Posts button from working.
