### ISSUE TITLE
Post Carousel breaks editor with wide template

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-blocks#666]
**Describe the bug**
When a post carousel block is used within a page using the "One Column Wide" template, it breaks the editor, pushing the settings sidebar off the edge of the screen where it is inaccessible because it's not possible to scroll to the right to find it. This makes the settings sidebar completely inaccessible.

**To Reproduce**
1. On a site with the Newspack theme, plugin and blocks plugin active
2. Add a new page and add a carousel block to the page content
3. Refresh the editor, it should be possible to see and use the settings sidebar
4. Change the template to "One Column Wide" and save
5. Refresh the editor if necessary, and observe that the settings sidebar is now inaccessible

**Expected behavior**
The carousel width should stay within the bounds of the post content area to avoid pushing elements off the screen.

**Comment by laurelfulford** [comment]
This looks like it's related to this issue in Gutenberg: https://github.com/WordPress/gutenberg/issues/27622

Jetpack includes a temporary fix (https://github.com/Automattic/jetpack/pull/17645), so enabling and connecting that plugin should solve the problem until a more permanent fix is included.

**Comment by laurelfulford** [comment]
Closing since this should be resolved by enabling/connecting Jetpack for now; if we decide we also want to bake that temporary fix into Newspack for the odd times Jetpack is not set up, that can be handled in a separate theme PR.
