### ISSUE TITLE
Subcategories cannot be accurately selected

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-blocks#669]
**Describe the bug**
There are two elements to this: a UI bug and a data bug. This may also be related to #207.

First of all, when attempting to select a subcategory as a filter, if there is more than one subcategory with the same name it's not possible to distinguish between them, as the UI simply lists the sub-category name without the parent as context, like so:

![Screenshot from 2021-01-15 12-00-10](https://user-images.githubusercontent.com/136342/104725582-30913e00-572a-11eb-8c2d-d081a5de0064.png)

Secondly, which ever of those subcategories are selected, only one of them is ever actually used in the filter, which means some of the subcategories can never be selected for the filter.

**To Reproduce**
1. Create a sub-category structure. Something like this (example IDs in brackets):

Category | Subcategory
--- | ---
Entertainment (4) | Feature (18)
Health (13) | Feature (19)
Politics (10) | Feature (20)

2. In a page, add three sets of homepage posts blocks and add filters as follows:

Block | Category | Subcategory
--- | --- | ---
1 | Entertainment (4) | Feature (18)
2 | Health (13) | Feature (19)
3 | Politics (10) | Feature (20)

Given the UI issue, you'll have to guess the right sub-category by considering the ordering of how they display in the Posts > Categories screen.

3. Review the code and observe that in each block the second category ID is always "18", when they should be "18", "19" and "20". See example:

```<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:newspack-blocks/homepage-articles {"postsToShow":1,"categories":["4","18"]} /--></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:newspack-blocks/homepage-articles {"postsToShow":1,"categories":["13","18"]} /--></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:newspack-blocks/homepage-articles {"postsToShow":1,"categories":["10","18"]} /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

**Expected behavior**
1. When categories with the same name are present it should be possible to distinguish between them in the UI based on context (such as parent/child relationship)
2. When selecting categories that have the same name, the correct category ID should be added to the block params JSON.

**Comment by thomasguillot** [comment]
I'm really not a fan of the `FormTokenField`. I think we should use a simple list view with a select (and a max-height with scroll bar), just like Core's "Categories" selection.
