### ISSUE TITLE
Blog Posts Block: "Load More Posts" doesn't work when AMP is set to "Standard"

### ISSUE THREAD

**Issue by liviopv** [Automattic/newspack-blocks#687]
**Describe the bug**
There's a conflict between the "Load More Posts" button and the AMP plugin when using the `Standard` AMP Template Mode

**To Reproduce**

1. Add the Blog Posts Block to a page
2. Toggle "Load More Posts"
3. Go to WP Admin > AMP > Settings
4. Set the **Template Mode** to Standard

**Screenshots**

Clicking on the button triggers these console errors/warnings:

![Screenshot](https://d.pr/i/NGJghv+)
Screenshot: https://d.pr/i/NGJghv

**Expected behavior**
Clicking on the button should load more posts

**What happened instead**
Clicking on the button doesn't change anything in the page and does not load more posts.

User-report: #3703008-zen

**Comment by dkoo** [comment]
@liviopv is this still replicable in production? I believe the update past v1.20 should have fixed this.

**Comment by dkoo** [comment]
Closing this for non-activity. I believe it was solved by the release mentioned above, but please feel free to reopen if it's still a problem.
