### ISSUE TITLE
Homepage Posts block shows different posts while logged in vs. not logged in

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-blocks#716]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
1. View the homepage for abq.news while logged in, and while not logged in—observe that different posts are shown for the Homepage Posts block at the top of the page.

**Expected behavior**
The posts shown should match regardless of login state, and since the block is the first one on the page, it should always show the most recent published post matching the query.

**Comment by claudiulodro** [comment]
Fixed in https://github.com/Automattic/newspack-popups/pull/484
