### ISSUE TITLE
Homepage Posts: display ALL categories instead of only first-assigned ONE

### ISSUE THREAD

**Issue by mmprep** [Automattic/newspack-blocks#732]
Hi,

In the Homepage Posts Block, I would like to display ALL categories assigned to posts.

According to the [documentation](https://newspack.pub/support/blocks/homepage-posts/), right now only one and first-assigned category is displayed in the meta field to the posts.

Can you please tell me how to remove this restriction?
I have no differentiation in importance and/or priority of categories, they are all equal.
And that's why I would like to display their whole list.

**Comment by laurelfulford** [comment]
Closing this issue as a duplicate of #596.
