### ISSUE TITLE
Donate Block: Add ability to customize amounts for all tiers and cadence

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-blocks#741]
Right now, the Donate Block is set to allow manual entry for only the Monthly cadence. The amounts for the One-Time and Annually tiers are then calculated from those entries automatically (*12). We established this based on a [request](https://github.com/Automattic/newspack-plugin/issues/242) for the One-Time donation back in 2019 by request from NRH. 

Things have changed a lot since then and NRH now allows customers to set whatever prices they want at whatever cadence they want. This causes problems when the Newspack donations only partially match as the site visitor may see different amounts when they go to checkout through NRH. Here's an example where the Donate Block had the One-Time values set at $120, $180 and $300. Selecting $120 or $180 causes the NRH checkout form to display the amount set for the third tier on their side ($365):

![Screen Shot 2021-04-13 at 14 57 28](https://user-images.githubusercontent.com/22805865/114767361-87141580-9d35-11eb-966c-2df8e1ee6c78.png)

The lack of flexibility in the donate block pricing hamstrings the flexibility of the NRH options. Customers either have to set them in the Donate block and then match to NRH or make them completely different in order to avoid this confusing disconnect on the checkout page. 

Ideally, it would be better to simply allow publishers to set their own pricing for all options in the Donate Block, rather than being tethered to the monthly options and pre-determined calculations.

**Comment by tmmbecker** [comment]
Mission Local has asked for this too.

**Comment by tmmbecker** [comment]
Mission Local has requested this too.

**Comment by thekaitlin** [comment]
Noting that Andrew at The Tributary told me today that this would be helpful for him/them as well.

**Comment by tmmbecker** [comment]
La Noticia has asked about this now too.

**Comment by allykmyta** [comment]
Cardinal has requested this as well.

**Comment by kosiew** [comment]
Requested here too - #32690979-hc

**Comment by gamebits** [comment]
PJP has asked for this as well.

**Comment by gamebits** [comment]
The Real News has asked for this feature as well.

**Comment by allykmyta** [comment]
Adding to this type of customization, it would be also helpful to be able to remove tabs entirely. e.g Keep monthly and one-time and remove annually. Requested by LNM

**Comment by dnalla1928** [comment]
The Pavlovic Today and Bethesda have both asked for this as well.
