### ISSUE TITLE
Introduce Support for Infinite Scroll

### ISSUE THREAD

**Issue by donalirl** [Automattic/newspack-blocks#748]
**Is your feature request related to a problem? Please describe.**
There isn't a way to make new posts load automatically as the reader scrolls down. 

**Describe the solution you'd like**
Introduce support for Infinite Scroll, possibly using Jetpack's existing feature:

https://jetpack.com/support/infinite-scroll/#theme

**Describe alternatives you've considered**
The Load more posts button can be used to load more posts, but infinite scroll is a more popular feature of the modern web browsing experience and it would be wonderful to introduce this to the Blog Posts block.

**Comment by tmmbecker** [comment]
Noting here that we've had a couple of requests from this recently from Newspack publishers.
