### ISSUE TITLE
Post Carousel: Add option for "slides per view"

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-blocks#749]
Currently the carousel defaults to showing a single slide at a time, with that slide sizing itself automatically to fill the horizontal space of the carousel block's container. The [Swiper library we use for this block](https://swiperjs.com/swiper-api) has an option called `slidesPerView` which should let us show more than one at a time, effectively making each slide visually smaller. We should add a block attribute to set this option.

**Comment by adekbadek** [comment]
Closed in #750
