### ISSUE TITLE
Donate block: display issues with large numbers

### ISSUE THREAD

**Issue by rickybanister** [Automattic/newspack-blocks#76]
![image](https://user-images.githubusercontent.com/437258/63359591-0243df00-c33b-11e9-8cc3-105ee6ff23c3.png)

I noticed a couple of issues using style 3 of the theme with the donate blocks, namely the height of the donate button, the tabs are pushing the labels out, and the prices are wrapping. I'm not sure if we can get away with a 'nowrap' setting here, but we may need to shrink some things.

**Comment by rickybanister** [comment]
I don't understand why, but I'm seeing `<br/>` tags rendered before all the text inside the form. I may have submitted the donation set up form with blank values when going through set up, could that have caused us to store br's?

**Comment by rickybanister** [comment]
Nevermind, I forgot that @claudiulodro went back through and configured things correctly.

**Comment by dkoo** [comment]
Don't think this is an issue anymore.
