### ISSUE TITLE
Post Carousel: Widget block preview flickers

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#788]
In WordPress 5.8 RC1, when you add the Post Carousel block to a widget space in the Customizer, or a widget space under WP Admin > Appearance, widgets, it does this weird, collapsing, flickery thing when you try to interact with it or blocks around it. 

In the following screen recording, I was hovering over and clicking on different blocks in the widget sidebar; the post carousel block is above the Donate block:

![post-carousel-block 2021-07-02 10_18_11](https://user-images.githubusercontent.com/177561/124308938-db51b900-db1e-11eb-8652-1843eade4942.gif)

**Comment by laurelfulford** [comment]
#791 was not the fix I'd hoped it would be; this one still needs some investigation!

**Comment by miguelpeixe** [comment]
I'm not sure if this will be of any help for now, but as I was testing #791 I noticed that the flickering occurs when the [`swiperInstance` is reinitialized by `componentDidUpdate`](https://github.com/Automattic/newspack-blocks/blob/e4f1e47aafe7fc382de278f1820f248b45b1d10f/src/blocks/carousel/edit.js#L66-L91).

**Comment by adekbadek** [comment]
Closed by #803 (please confirm @laurelfulford)

**Comment by laurelfulford** [comment]
@adekbadek this seems to fix it for me, too -- no amount of clicking around or adding carousels can get the issue happening on my test site again. Thank you! 🙌
