### ISSUE TITLE
Homepage Block: Inline, text-only version

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#80]
Not sure if there is much needed for this -- it could just be CSS-based -- but we need a text-only simple version of the block, like: 

![image](https://user-images.githubusercontent.com/177561/63380870-48556e80-c34c-11e9-87b4-c51bd399172d.png)

It can be done with plain text, but if we have a way to do it with the block, it won't take as much work to style right.

**Comment by dkoo** [comment]
Feel free to reopen if still needed, but I think I've seen most publishers use Campaigns for this instead.
