### ISSUE TITLE
Post Carousel: Font size doesn't change, regardless how many slides are shown

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#844]
**Describe the bug**
You can now set the Post Carousel to display 2 or 3 posts at once, but the font size doesn't change at all, and at smaller sizes, it feels like the post title should scale down a bit. 

![image](https://user-images.githubusercontent.com/177561/130679326-11581d81-892d-4210-921a-8ed7bbf6caed.png)

We can also address this in the theme; I feel like it may make more sense here, but I'm open to feedback on that!

**Comment by tmmbecker** [comment]
Atlanta Civic just reported as well.
