### ISSUE TITLE
Post Carousel block doesn't display the featured images

### ISSUE THREAD

**Issue by Robertght** [Automattic/newspack-blocks#851]
**Describe the bug**
We have a case in 4257832-zen for a couple of post carousels that are not displaying the featured images of the posts on the frontend, despite showing up in the editor.

**To Reproduce**
1. Create a new page and add a Post Carousel block
2. I used the featured tag to have the posts that had a featured image attached 
3. Check the results in the editor vs frontend.

The user's site has the Canard theme, but it's the same with TwentyTwenty-One.

I used this as a workaround for Canard:

```
.wp-block-newspack-blocks-carousel .post-thumbnail img {
    opacity: 1 !important;
    position: absolute !important;
    top: 0 !important;
}

/* Temp fix for the post carousel images for firefox | xxxxx-zen rg */
.wp-block-newspack-blocks-carousel .swiper-slide {
    height: 75vh !important;
}

```

**Screenshots**

Frontend VS Editor

![image](https://user-images.githubusercontent.com/6737345/131471058-485f5338-5b83-48c6-9a62-a73a5e5306fa.png)

**Expected behavior**

To have the images appear on the carousel

**Comment by Gustavo-Hilario** [comment]
#4257832-zen

After investigating more about this issue, we figured out this usually happens when we are displaying the Post Carousel block using the posts categories. A workaround can be displaying blogs posts with tags.

However, this is also unstable. When selecting the display settings (categories or tags), the selected posts cannot appear in the Editor, and when publishing the page, the featured images can randomly show all images, a few of them or none.

**Comment by ArSn** [comment]
Just to add a little more information from my own testing: The issue appears and disappears apparently randomly when one refreshes the page over and over. Is it possible that there is some sort of race condition, e.g. because the carousel does not know the size of the images yet?

**Comment by helenaartmann** [comment]
Got a user on chat having the same issue using the Dara theme. Tried on Chrome, same issue. Tried the above workaround and it didn't work. 6626984-hc

**Comment by Robertght** [comment]
I have reviewed the original case and updated the CSS code workaround.

**Comment by aleone89** [comment]
There's another report of this bug here: https://github.com/Automattic/newspack-blocks/issues/851 Also tried the work around, but this did not work.

**Comment by supernovia** [comment]
We have another case [here](https://wordpress.com/forums/topic/post-carousel-not-displaying-featured-images/):

The workaround didn't work.

**Comment by supernovia** [comment]
I think I've figured out, at least in the case of Twenty Twenty One, that the problem only occurs if someone has unchecked the option to show featured images on individual posts. And in themes that make the featured image appear at full width, that's a fairly popular thing to uncheck, especially on free sites.

The themes I've spot checked seem affected.

**Comment by hgwaltney** [comment]
Another case #4648721-zen

CSS workaround didn't help here, but checking the option to display featured images on pages did the trick

**Comment by flameslash** [comment]
Reporting this as well here 4829894-zd-woothemes. Provided the workaround to enable featured images on pages via content options in customizer.

**Comment by Camaropilot** [comment]
Another report, 4964916-zen. CSS did not work, Display on pages did (Customizer -> Content Options).

**Comment by donalirl** [comment]
Another case in #36391138 with Gateway theme. Content Options checkbox solved it.

**Comment by taipeicoder** [comment]
Another case in 5936728-zd-woothemes. Content Options checkbox solved it.

**Comment by mgozdis** [comment]
Another report here on a Simple site with Rockfield theme. Displaying featured images on Pages was uncheck without user intervention. Re-enabling featured images on Pages allowed the Post Carousel to work: 7600512-zd-a8c

**Comment by anomiex** [comment]
FYI, Simple needed an additional change to pick up the fix. Details at https://github.com/Automattic/jetpack/issues/29286#issuecomment-1898653522.
