### ISSUE TITLE
Donate Block: Multiple tabs cause issues

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#86]
**Describe the bug**
This is an odd edge case, but if you have more than one donate block on a page, no matter what one you try to switch tabs on, it will only affect the first one:

https://cloudup.com/cTolPNMsnnT

**To Reproduce**
1. Add two donate blocks to a page.
2. Click on the tabs of the second one.
3. Note that nothing happens to that block, but the first one changes.

**Comment by claudiulodro** [comment]
This should be investigated further. I'm not sure what the best solution is without doing a deep investigation, but it should be possible to solve. The tricky part is that it's all done with CSS, so it's not super straightforward. :)
