### ISSUE TITLE
Homepage post block add advanced custom field

### ISSUE THREAD

**Issue by bhavikap45** [Automattic/newspack-blocks#862]
I want to add an advanced custom field to the post blocks and I want to do this in the child theme and not the plugin itself. Please advise how this can be possible.

**Comment by adekbadek** [comment]
Hi, if I understand correctly, you have some custom fields defined on a post, and you'd like these displayed on in the Homepage Posts block. If so, this is not something we plan to support for the time being. 
Feel free to reopen if I've misinterpreted the feature request.
