### ISSUE TITLE
Homepage Posts: HTML support stopped working in custom excerpts

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-blocks#888]
By request from CT News Junkie, it would be helpful to add the link capabilities in excerpts. Could we mimic what's been done for HTML support in Subtitles and add it to the excerpts as well?

**Comment by laurelfulford** [comment]
@tmmbecker Right now the block uses WordPress's `the_excerpt()` function to pull the auto-generated excerpts, which strips the HTML automatically. I'm personally leery about changing that exactly, since it'll impact both Newspack sites and WP.com (and then we have to deal with things like avoiding splitting up HTML tags when the excerpt is cropped). 

In this case, would it work to add the link to the Custom Excerpt instead? It doesn't get stripped out there (I'm not sure it'll allow _all_ HTML, but it does allow the basics); the downside is it's not a nice WYSIWYG editor, so it's not as nice/easy to use. 

Let me know what you think!

**Comment by tmmbecker** [comment]
@laurelfulford totally my bad on this one for not specifying that this would be for the Custom Excerpt. So what you propose is actually what I had in mind! I'm so sorry for not being clearer.

**Comment by laurelfulford** [comment]
Copying this over from #1346 (thanks @Robertght!) 

> **Describe the bug**
> Custom HTML items like links will get stripped from manual post excerpts.
>
> **To Reproduce**
> Steps to reproduce the behavior:
>
> 1. Publish a post or two and make sure it has a custom excerpt that contains some Custom HTML(I tested with links)
> 2. Create a new page and add the Blog Posts block.
> 3. Enable the excerpts and make sure the Custom HTML-related content is visible(adjust the word count)
> 4. Publish the page and check the results
>
> **Expected behavior**
>The text gets outputted correctly, but the custom HTML isn't so instead of <a href="link-to-some-page">link</a> we get just "link"
> 
> This was reported in 5859415-zen and as a workaround a user can have the posts on the default post archive of that theme use the [Query Loop Block](https://wordpress.com/en/support/full-site-editing/theme-blocks/query-loop-block/).
> 
> The user claims this was working fine Saturday, but it changed out of nowhere.
>
> Initially reported in Slack: p1673529481724749-slack-C01C378QWRX

The [change that caused this](https://github.com/Automattic/newspack-blocks/pull/874#issuecomment-929630315) was included in the 1.39.0 block release, and [WP.com was just synced from 1.37.1 to 1.60](https://github.com/Automattic/newspack-blocks/issues/888), so it makes sense that this is being reported as a new issue there.

**Comment by liviopv** [comment]
Another WordPress.com user report:

- [ ] 5865814-zd-woothemes

**Comment by liviopv** [comment]
The closest workaround to this is using the Query Loop Block with the Post Content Block in it and then using the More Block in each post to tweak how much content is displayed. Not ideal, but it will show formatting for "excerpts" in post lists.

**Comment by ericdye** [comment]
Another WordPress.com user has reported this. In this case, line breaks are being ignored.

- [ ] 5875257-zd-woothemes
