### ISSUE TITLE
Make a post carousel stick to the *bottom* of the page.

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-blocks#891]
Ithaca would like to keep their sponsors carousel on the page  even after the scroll by having it appear at the bottom of the page and not move up. It's a way to add visibility for sponsors.

**Comment by laurelfulford** [comment]
Closing and moving to a support request in Asana, as this isn't a block-level option we can add and have work everywhere the block is used -- it's more site-specific, serving a very specific use case.
