### ISSUE TITLE
Article Block: Kill the more link

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#94]
Right now when you use the 'More' button, it goes to the archive page of the current category (soon to be expanded).

Is there a smart way to offset where you end up when clicking 'more' -- like an anchor, or even offsetting the posts on the archive page?

Note that for either, you may have a block with three articles, but there could be articles from that same category further up the page -- so the offset would need to be based on which articles these are (the third, fourth and fifth on the page from this category?), not just how many they are (three posts from this category).

**Comment by obenland** [comment]
With our efforts to replace the Posts List block on dotcom with Newspack's Homepage Articles block in https://github.com/Automattic/Dotcom-roadmap/issues/55 we're running into a back combat issue with the missing more button.

@laurelfulford @rickybanister I wondered if you were open to bringing that button back, if we changed the premise from it being a "View more" link to a "View All" link?

**Comment by rickybanister** [comment]
I'm ok with that as long as we retain the toggle to hide/show it.

**Comment by laurelfulford** [comment]
I'd be open to re-adding the button, too, but I should add a bit more context around why we removed it, that I didn't get into above: the button originally linked to the current block's category archive page (at the time, it was the only way you could sort posts). If the block was displaying all posts, it defaulted to the blog posts page. 

As the query for the block got more complicated, letting you select posts by category, tags, authors, a mix of all three, it got harder to predict where the 'More' link should go. It also made less sense when paired with the option to pick a specific individual post. 

For us, the easiest fix was to remove it; if we re-add the button, we just need to figure out where it should go. The easiest option would be to just point it to the blog posts page. Or perhaps there's a clever way to handle the more complicated queries that we just didn't figure out. 

Let me know if you'd like me to create a fresh issue for this, @obenland, and we can hash out the details there.

**Comment by obenland** [comment]
Yeah let's do that! I'm happy to poke around WP's link template and see if we can make that work sanely

**Comment by laurelfulford** [comment]
Great! Made a new issue here: https://github.com/Automattic/newspack-blocks/issues/154
