### ISSUE TITLE
Post Carousel displays broken thumbnail on Preview

### ISSUE THREAD

**Issue by zaguiini** [Automattic/newspack-blocks#972]
**Describe the bug**

The block tries to display featured images even though the post doesn't have one.  This only happens inside Preview. The live site looks fine.

**To Reproduce**
1. Include `Post Carousel` block into the editor.

**Screenshots**

![image](https://user-images.githubusercontent.com/26530524/145877581-97db23c8-338e-4b01-b168-cdb94db2a23f.png)

I'm getting `undefined/newspack-800x600.jpg` as image sources, even though my posts don't have featured images. Is it a placeholder? If yes, why am I getting `undefined` as the host URL?

**Expected behavior**

To hide the thumbnail image when there's none or to display the placeholder correctly.

**Context**

WPCOM running `v12.1.0` Gutenberg on Quadrat theme.

**Comment by laurelfulford** [comment]
I was able to recreate this on a simple site on WP.com, but not on my localhost.

**Comment by Greatdane** [comment]
📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Unable to replicate this, just see a blank screen (intended for this block) in the editor, live and preview on both simple and AT;

<img width="834" alt="Markup 2022-06-30 at 11 28 13" src="https://user-images.githubusercontent.com/5075840/176580145-1b8185fd-244f-48f3-a704-4bb61ae1c8e0.png">

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)
